module Vehicle.Data.Code.ModuleInterface where

import Data.Map (Map)
import Data.Serialize (Serialize)
import Data.Set (Set)
import GHC.Generics (Generic)
import Vehicle.Compile.Prelude
import Vehicle.Compile.Type.Core (InstanceDatabase, emptyInstanceDatabase)
import Vehicle.Data.Builtin.Standard.Core
import Vehicle.Data.Code.Value

--------------------------------------------------------------------------------
--- ScopingState

--- | The public interface to a module, i.e. the set of declarations that
--- it exports.
data ModuleTypingState builtin = ModuleTypingState
  { recordIdentifiersByField :: Map FieldName (Identifier, Telescope builtin),
    recordIdentifiersByFields :: Map (Set FieldName) (Identifier, Telescope builtin),
    fieldsByRecordIdentifier :: Map Identifier (Set FieldName),
    declsIdentifiersByName :: Map Name Identifier,
    instanceDatabase :: InstanceDatabase builtin,
    builtinDatabase :: Map builtin (Type builtin)
  }
  deriving (Generic)

instance Serialize (ModuleTypingState Builtin)

emptyModuleTypingState :: (Ord builtin) => ModuleTypingState builtin
emptyModuleTypingState =
  ModuleTypingState
    { recordIdentifiersByField = mempty,
      recordIdentifiersByFields = mempty,
      fieldsByRecordIdentifier = mempty,
      declsIdentifiersByName = mempty,
      instanceDatabase = emptyInstanceDatabase,
      builtinDatabase = mempty
    }

--------------------------------------------------------------------------------
-- Interface to a module

-- | The state generated by type-checking a module
data ModuleInterface builtin = ModuleInterface
  { typedModule :: Module builtin,
    typingState :: ModuleTypingState builtin
  }
  deriving (Generic)

instance Serialize (ModuleInterface Builtin)

--------------------------------------------------------------------------------
-- ModuleContext

type ImportedModuleContext builtin =
  [(ModulePath, ModuleInterface builtin, FreeEnv builtin)]

lookupInCombinedContext ::
  (ModuleTypingState builtin -> Maybe a) ->
  ModuleTypingState builtin ->
  ImportedModuleContext builtin ->
  Maybe a
lookupInCombinedContext lookupValue currentInterface importedCtx =
  case lookupValue currentInterface of
    Just result -> Just result
    Nothing -> do
      let lookupInImport (_, moduleInterface, _) = lookupValue $ typingState moduleInterface
      firstJust lookupInImport importedCtx

concatInCombinedContext ::
  (Monoid a) =>
  (ModuleInterface builtin -> interface) ->
  (interface -> a) ->
  interface ->
  ImportedModuleContext builtin ->
  a
concatInCombinedContext getInterface getValue currentInterface importedCtx = do
  mconcat $ fmap getValue (currentInterface : fmap (\(_, interface, _) -> getInterface interface) importedCtx)

mergeImportedFreeEnvs :: ImportedModuleContext builtin -> FreeEnv builtin
mergeImportedFreeEnvs ctx = mconcat $ fmap (\(_, _, env) -> env) ctx
