module Vehicle.Data.Code.ModuleInterface where

import Data.Map (Map)
import Data.Serialize (Serialize)
import Data.Set (Set)
import GHC.Generics (Generic)
import Vehicle.Compile.Prelude
import Vehicle.Compile.Type.Core (InstanceDatabase, emptyInstanceDatabase)
import Vehicle.Data.Builtin.Standard.Core
import Vehicle.Data.Code.Value

--------------------------------------------------------------------------------
--- ScopingState

--- | The public interface to a module, i.e. the set of declarations that
--- it exports.
data ModuleScopingInterface builtin = ModuleScopingInterface
  { recordIdentifiersByField :: Map FieldName (Identifier, Telescope builtin),
    recordIdentifiersByFields :: Map (Set FieldName) (Identifier, Telescope builtin),
    fieldsByRecordIdentifier :: Map Identifier (Set FieldName),
    declsIdentifiersByName :: Map Name Identifier
  }
  deriving (Generic)

instance Serialize (ModuleScopingInterface Builtin)

emptyModuleScopingInterface :: ModuleScopingInterface builtin
emptyModuleScopingInterface =
  ModuleScopingInterface
    { recordIdentifiersByField = mempty,
      recordIdentifiersByFields = mempty,
      fieldsByRecordIdentifier = mempty,
      declsIdentifiersByName = mempty
    }

data ModuleTypingInterface builtin = ModuleTypingInterface
  { instanceDatabase :: InstanceDatabase builtin,
    builtinDatabase :: Map builtin (Type builtin)
  }
  deriving (Generic)

instance Serialize (ModuleTypingInterface Builtin)

emptyModuleTypingInterface :: (Ord builtin) => ModuleTypingInterface builtin
emptyModuleTypingInterface =
  ModuleTypingInterface
    { instanceDatabase = emptyInstanceDatabase,
      builtinDatabase = mempty
    }

--------------------------------------------------------------------------------
-- Interface to a module

-- | The state generated by type-checking a module
data ModuleInterface builtin = ModuleInterface
  { typedModule :: Module builtin,
    scopingInterface :: ModuleScopingInterface builtin,
    typingInterface :: ModuleTypingInterface builtin
  }
  deriving (Generic)

instance Serialize (ModuleInterface Builtin)

--------------------------------------------------------------------------------
-- ModuleContext

type ImportedModuleContext builtin = [(ModulePath, ModuleInterface builtin, FreeEnv builtin)]

lookupInCombinedContext ::
  (ModuleInterface builtin -> interface) ->
  (interface -> Maybe a) ->
  interface ->
  ImportedModuleContext builtin ->
  Maybe a
lookupInCombinedContext getInterface lookupValue currentInterface importedCtx =
  case lookupValue currentInterface of
    Just result -> Just result
    Nothing -> do
      let lookupInImport (_, moduleInterface, _) = lookupValue $ getInterface moduleInterface
      firstJust lookupInImport importedCtx

concatInCombinedContext ::
  (Monoid a) =>
  (ModuleInterface builtin -> interface) ->
  (interface -> a) ->
  interface ->
  ImportedModuleContext builtin ->
  a
concatInCombinedContext getInterface getValue currentInterface importedCtx = do
  mconcat $ fmap getValue (currentInterface : fmap (\(_, interface, _) -> getInterface interface) importedCtx)

mergeImportedFreeEnvs :: ImportedModuleContext builtin -> FreeEnv builtin
mergeImportedFreeEnvs ctx = mconcat $ fmap (\(_, _, env) -> env) ctx
