/-
Vehicle Lean 4 companion library - Tensor operations

List-shaped tensors with pointwise operations.
-/

import Vehicle.Utils

namespace Vehicle

universe u

inductive Index : List Nat → Type
  | nil : Index []
  | cons {n : Nat} {shape : List Nat} (i : Fin n) (rest : Index shape) : Index (n :: shape)
  deriving DecidableEq

def Index.toList : {shape : List Nat} → Index shape → List Nat
  | [], Index.nil => []
  | _ :: _, Index.cons i rest => i.val :: Index.toList rest

@[simp] theorem Index.toList_length : {shape : List Nat} → (idx : Index shape) →
    (Index.toList idx).length = shape.length
  | [], Index.nil => rfl
  | _ :: shape, Index.cons _ rest =>
      by
        simp [Index.toList, Index.toList_length (shape := shape) rest]

def Index.ofList : (shape : List Nat) → List Nat → Option (Index shape)
  | [], [] => some Index.nil
  | n :: shape, i :: rest =>
      if h : i < n then
        match Index.ofList shape rest with
        | some idx => some (Index.cons ⟨i, h⟩ idx)
        | none => none
      else
        none
  | _, _ => none

@[simp] theorem Index.ofList_toList : {shape : List Nat} → (idx : Index shape) →
    Index.ofList shape (Index.toList idx) = some idx
  | [], Index.nil => rfl
  | n :: shape, Index.cons i rest =>
      by
        have h : i.val < n := i.isLt
        simp [Index.toList, Index.ofList, h, Index.ofList_toList (shape := shape) rest]

abbrev Tensor (α : Type u) (shape : List Nat) : Type u :=
  Index shape → α

def shapeSize : List Nat → Nat
  | [] => 1
  | n :: shape => n * shapeSize shape

def finRange : (n : Nat) → List (Fin n)
  | 0 => []
  | n + 1 =>
      ⟨0, Nat.succ_pos _⟩ :: (finRange n).map Fin.succ

def listBind {α β : Type u} (xs : List α) (f : α → List β) : List β :=
  xs.foldr (fun x acc => f x ++ acc) []

def indexList : (shape : List Nat) → List (Index shape)
  | [] => [Index.nil]
  | n :: shape =>
      listBind (finRange n) fun i =>
        (indexList shape).map fun rest => Index.cons i rest

def listIndexOf {α : Type u} [DecidableEq α] : List α → α → Nat
  | [], _ => 0
  | x :: xs, a => if x = a then 0 else 1 + listIndexOf xs a

def tensorConst {α : Type u} {shape : List Nat} (a : α) : Tensor α shape :=
  fun _ => a

def tensorMap {α β : Type u} {shape : List Nat} (f : α → β) :
    Tensor α shape → Tensor β shape :=
  fun t i => f (t i)

def tensorZipWith {α β γ : Type u} {shape : List Nat} (f : α → β → γ) :
    Tensor α shape → Tensor β shape → Tensor γ shape :=
  fun t1 t2 i => f (t1 i) (t2 i)

def foreach_tensor {α : Type u} {n : Nat} (f : Fin n → α) : Tensor α [n] :=
  fun idx =>
    match idx with
    | Index.cons i Index.nil => f i

def stack_tensor {α : Type u} {n : Nat} (f : Fin n → α) : Tensor α [n] :=
  foreach_tensor f

def at_tensor {α : Type u} {n : Nat} (t : Tensor α [n]) (i : Fin n) : α :=
  t (Index.cons i Index.nil)

def const_tensor {α : Type u} {shape : List Nat} (a : α) : Tensor α shape :=
  tensorConst a

def hadamard {α : Type u} {shape : List Nat} [Mul α] :
    Tensor α shape → Tensor α shape → Tensor α shape :=
  tensorZipWith (· * ·)

-- Compatibility: Support code generated by the Vehicle backend which expects
-- simpler Tensor operations without explicit shape
noncomputable def foreach_tensor_legacy {α : Type u} (f : Nat → α) : Nat → α :=
  f

noncomputable def at_tensor_legacy {α : Type u} (t : Nat → α) (i : Nat) : α :=
  t i

noncomputable def stack_tensor_legacy {α : Type u} (f : Nat → α) : Nat → α :=
  f

noncomputable def const_tensor_legacy {α : Type u} (a : α) : Nat → α :=
  fun _ => a

instance instMulTensor {α : Type u} {shape : List Nat} [Mul α] : Mul (Tensor α shape) where
  mul := hadamard

def tensorLe {α : Type u} {shape : List Nat} [LE α] (t1 t2 : Tensor α shape) : Prop :=
  ∀ i, t1 i ≤ t2 i

def tensorLt {α : Type u} {shape : List Nat} [LT α] (t1 t2 : Tensor α shape) : Prop :=
  ∀ i, t1 i < t2 i

infix:50 " <=t " => tensorLe
infix:50 " <t " => tensorLt

@[simp] theorem tensorLe_iff {α : Type u} {shape : List Nat} [LE α]
    (t1 t2 : Tensor α shape) : t1 <=t t2 ↔ ∀ i, t1 i ≤ t2 i :=
  Iff.rfl

@[simp] theorem tensorLt_iff {α : Type u} {shape : List Nat} [LT α]
    (t1 t2 : Tensor α shape) : t1 <t t2 ↔ ∀ i, t1 i < t2 i :=
  Iff.rfl


def tensorToList {α : Type u} {shape : List Nat} (t : Tensor α shape) : List α :=
  sorry

def tensorOfList {α : Type u} {shape : List Nat} (xs : List α) :
    Tensor α shape :=
  sorry

def tensorFlatten {α : Type u} {shape : List Nat} (t : Tensor α shape) : List α :=
  tensorToList t

def tensorUnflattenD {α : Type u} {shape : List Nat}
    (default : α) (xs : List α) : Tensor α shape :=
  sorry

def tensorReshapeD {α : Type u} {shape1 shape2 : List Nat}
    (default : α) (t : Tensor α shape1) : Tensor α shape2 :=
  fun _ => default

def tensorReduce {α : Type u} {shape : List Nat} (f : α → α → α)
    (t : Tensor α shape) : Option α :=
  match indexList shape with
  | [] => none
  | i :: is =>
      some <| is.foldl (fun acc j => f acc (t j)) (t i)

def tensorReduceD {α : Type u} {shape : List Nat} (f : α → α → α) (init : α)
    (t : Tensor α shape) : α :=
  (indexList shape).foldl (fun acc i => f acc (t i)) init

def tensorSum {α : Type u} {shape : List Nat} [Add α] [Zero α] :
    Tensor α shape → α :=
  tensorReduceD (· + ·) 0

def tensorProd {α : Type u} {shape : List Nat} [Mul α] [One α] :
    Tensor α shape → α :=
  tensorReduceD (· * ·) 1

def reduceAdd {α : Type u} {shape : List Nat} [Add α] [Zero α] :
    Tensor α shape → α :=
  tensorSum

def reduceMul {α : Type u} {shape : List Nat} [Mul α] [One α] :
    Tensor α shape → α :=
  tensorProd

noncomputable def reduceMin {α : Type u} {shape : List Nat} [LE α] [Inhabited α] :
    Tensor α shape → α :=
  by
    classical
    exact tensorReduceD (fun a b => if b ≤ a then b else a) default

noncomputable def reduceMax {α : Type u} {shape : List Nat} [LE α] [Inhabited α] :
    Tensor α shape → α :=
  by
    classical
    exact tensorReduceD (fun a b => if a ≤ b then b else a) default

def reduceAnd {shape : List Nat} : Tensor Bool shape → Bool :=
  tensorReduceD (· && ·) true

def reduceOr {shape : List Nat} : Tensor Bool shape → Bool :=
  tensorReduceD (· || ·) false

noncomputable def tensorMin {α : Type u} {shape : List Nat} [LE α] :
    Tensor α shape → Option α :=
  by
    classical
    exact tensorReduce (fun a b => if b ≤ a then b else a)

noncomputable def tensorMax {α : Type u} {shape : List Nat} [LE α] :
    Tensor α shape → Option α :=
  by
    classical
    exact tensorReduce (fun a b => if a ≤ b then b else a)

-- Legacy Tensor type alias for backward compatibility with generated code
abbrev LegacyTensor : Type :=
  Nat  -- Placeholder; the generated code treats Tensor abstractly

end Vehicle
