-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

open import Data.Unit

module MyTestModule where

e1 : let x = ⊤ in x
e1 = checkProperty record
  { databasePath = DATABASE_PATH
  ; propertyUUID = ????
  }