"""Auto-generated by vehicle-lang from acasXu-record.vcl. Do not edit."""



from __future__ import annotations



import torch



from jaxtyping import Float

from torch import Tensor





class InputVector(torch.Tensor):  # type: ignore[misc]

    # Make torch.* ops return plain Tensor, not this subclass.

    __torch_function__ = torch._C._disabled_torch_function_impl



    _FIELDS: tuple[str, ...] = ('distanceToIntruder', 'angleToIntruder', 'intruderHeading', 'speed', 'intruderSpeed')

    _FLAT_WIDTH: int = 5

    _FIELD_SLOTS: dict[str, tuple[int, int]] = {

        'distanceToIntruder': (0, 1),

        'angleToIntruder': (1, 2),

        'intruderHeading': (2, 3),

        'speed': (3, 4),

        'intruderSpeed': (4, 5),

    }



    @staticmethod

    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> 'InputVector':

        if _from_tensor is not None:

            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]

        slabs = []

        v_distanceToIntruder = torch.as_tensor(fields['distanceToIntruder'])

        slabs.append(v_distanceToIntruder.reshape(*v_distanceToIntruder.shape, 1))

        v_angleToIntruder = torch.as_tensor(fields['angleToIntruder'])

        slabs.append(v_angleToIntruder.reshape(*v_angleToIntruder.shape, 1))

        v_intruderHeading = torch.as_tensor(fields['intruderHeading'])

        slabs.append(v_intruderHeading.reshape(*v_intruderHeading.shape, 1))

        v_speed = torch.as_tensor(fields['speed'])

        slabs.append(v_speed.reshape(*v_speed.shape, 1))

        v_intruderSpeed = torch.as_tensor(fields['intruderSpeed'])

        slabs.append(v_intruderSpeed.reshape(*v_intruderSpeed.shape, 1))

        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]



    @classmethod

    def from_tensor(cls, t: Tensor) -> 'InputVector':

        return t.as_subclass(cls)  # type: ignore[no-any-return]



    def to_tensor(self) -> Tensor:

        return self.as_subclass(torch.Tensor)



    @property

    def distanceToIntruder(self) -> Float[Tensor, ""]:

        lo, hi = InputVector._FIELD_SLOTS['distanceToIntruder']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def angleToIntruder(self) -> Float[Tensor, ""]:

        lo, hi = InputVector._FIELD_SLOTS['angleToIntruder']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def intruderHeading(self) -> Float[Tensor, ""]:

        lo, hi = InputVector._FIELD_SLOTS['intruderHeading']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def speed(self) -> Float[Tensor, ""]:

        lo, hi = InputVector._FIELD_SLOTS['speed']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def intruderSpeed(self) -> Float[Tensor, ""]:

        lo, hi = InputVector._FIELD_SLOTS['intruderSpeed']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])





class OutputVector(torch.Tensor):  # type: ignore[misc]

    # Make torch.* ops return plain Tensor, not this subclass.

    __torch_function__ = torch._C._disabled_torch_function_impl



    _FIELDS: tuple[str, ...] = ('clearOfConflict', 'weakLeft', 'weakRight', 'strongLeft', 'strongRight')

    _FLAT_WIDTH: int = 5

    _FIELD_SLOTS: dict[str, tuple[int, int]] = {

        'clearOfConflict': (0, 1),

        'weakLeft': (1, 2),

        'weakRight': (2, 3),

        'strongLeft': (3, 4),

        'strongRight': (4, 5),

    }



    @staticmethod

    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> 'OutputVector':

        if _from_tensor is not None:

            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]

        slabs = []

        v_clearOfConflict = torch.as_tensor(fields['clearOfConflict'])

        slabs.append(v_clearOfConflict.reshape(*v_clearOfConflict.shape, 1))

        v_weakLeft = torch.as_tensor(fields['weakLeft'])

        slabs.append(v_weakLeft.reshape(*v_weakLeft.shape, 1))

        v_weakRight = torch.as_tensor(fields['weakRight'])

        slabs.append(v_weakRight.reshape(*v_weakRight.shape, 1))

        v_strongLeft = torch.as_tensor(fields['strongLeft'])

        slabs.append(v_strongLeft.reshape(*v_strongLeft.shape, 1))

        v_strongRight = torch.as_tensor(fields['strongRight'])

        slabs.append(v_strongRight.reshape(*v_strongRight.shape, 1))

        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]



    @classmethod

    def from_tensor(cls, t: Tensor) -> 'OutputVector':

        return t.as_subclass(cls)  # type: ignore[no-any-return]



    def to_tensor(self) -> Tensor:

        return self.as_subclass(torch.Tensor)



    @property

    def clearOfConflict(self) -> Float[Tensor, ""]:

        lo, hi = OutputVector._FIELD_SLOTS['clearOfConflict']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def weakLeft(self) -> Float[Tensor, ""]:

        lo, hi = OutputVector._FIELD_SLOTS['weakLeft']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def weakRight(self) -> Float[Tensor, ""]:

        lo, hi = OutputVector._FIELD_SLOTS['weakRight']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def strongLeft(self) -> Float[Tensor, ""]:

        lo, hi = OutputVector._FIELD_SLOTS['strongLeft']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def strongRight(self) -> Float[Tensor, ""]:

        lo, hi = OutputVector._FIELD_SLOTS['strongRight']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])





class UnnormalisedInputVector(torch.Tensor):  # type: ignore[misc]

    # Make torch.* ops return plain Tensor, not this subclass.

    __torch_function__ = torch._C._disabled_torch_function_impl



    _FIELDS: tuple[str, ...] = ('uDistanceToIntruder', 'uAngleToIntruder', 'uIntruderHeading', 'uSpeed', 'uIntruderSpeed')

    _FLAT_WIDTH: int = 5

    _FIELD_SLOTS: dict[str, tuple[int, int]] = {

        'uDistanceToIntruder': (0, 1),

        'uAngleToIntruder': (1, 2),

        'uIntruderHeading': (2, 3),

        'uSpeed': (3, 4),

        'uIntruderSpeed': (4, 5),

    }



    @staticmethod

    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> 'UnnormalisedInputVector':

        if _from_tensor is not None:

            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]

        slabs = []

        v_uDistanceToIntruder = torch.as_tensor(fields['uDistanceToIntruder'])

        slabs.append(v_uDistanceToIntruder.reshape(*v_uDistanceToIntruder.shape, 1))

        v_uAngleToIntruder = torch.as_tensor(fields['uAngleToIntruder'])

        slabs.append(v_uAngleToIntruder.reshape(*v_uAngleToIntruder.shape, 1))

        v_uIntruderHeading = torch.as_tensor(fields['uIntruderHeading'])

        slabs.append(v_uIntruderHeading.reshape(*v_uIntruderHeading.shape, 1))

        v_uSpeed = torch.as_tensor(fields['uSpeed'])

        slabs.append(v_uSpeed.reshape(*v_uSpeed.shape, 1))

        v_uIntruderSpeed = torch.as_tensor(fields['uIntruderSpeed'])

        slabs.append(v_uIntruderSpeed.reshape(*v_uIntruderSpeed.shape, 1))

        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]



    @classmethod

    def from_tensor(cls, t: Tensor) -> 'UnnormalisedInputVector':

        return t.as_subclass(cls)  # type: ignore[no-any-return]



    def to_tensor(self) -> Tensor:

        return self.as_subclass(torch.Tensor)



    @property

    def uDistanceToIntruder(self) -> Float[Tensor, ""]:

        lo, hi = UnnormalisedInputVector._FIELD_SLOTS['uDistanceToIntruder']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def uAngleToIntruder(self) -> Float[Tensor, ""]:

        lo, hi = UnnormalisedInputVector._FIELD_SLOTS['uAngleToIntruder']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def uIntruderHeading(self) -> Float[Tensor, ""]:

        lo, hi = UnnormalisedInputVector._FIELD_SLOTS['uIntruderHeading']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def uSpeed(self) -> Float[Tensor, ""]:

        lo, hi = UnnormalisedInputVector._FIELD_SLOTS['uSpeed']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])



    @property

    def uIntruderSpeed(self) -> Float[Tensor, ""]:

        lo, hi = UnnormalisedInputVector._FIELD_SLOTS['uIntruderSpeed']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape(self.shape[:-1])