version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the documentation
  - package-ecosystem: "pip"
    directory: "/docs-source"
    schedule:
      interval: "weekly"

  # Maintain dependencies for py-vehicle-cli
  - package-ecosystem: "pip"
    directory: "/py-vehicle-cli"
    schedule:
      interval: "weekly"

  # Maintain dependencies for py-vehicle-tensorflow
  - package-ecosystem: "pip"
    directory: "/py-vehicle-tensorflow"
    schedule:
      interval: "weekly"
