version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the documentation
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"

  # Maintain dependencies for vehicle-python
  - package-ecosystem: "pip"
    directory: "/vehicle-python"
    schedule:
      interval: "weekly"
