-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Data.Unit
open import Data.Empty
open import Data.Product
open import Data.Nat as ℕ using (ℕ)
open import Data.Fin as Fin using (Fin; #_)

module simple-let-temp-output where

abstract
  e1 : let x = ⊤ in let y = ⊥ in x × y
  e1 = checkSpecification record
    { proofCache   = "/home/matthew/Code/AISEC/vehicle/proofcache.vclp"
    }

abstract
  e2 : let y = # 1 in y Fin.≥ # 2
  e2 = checkSpecification record
    { proofCache   = "/home/matthew/Code/AISEC/vehicle/proofcache.vclp"
    }

e3 : ℕ
e3 = let y = 1 ℕ.+ 1 in y

e4 : ℕ → ℕ
e4 x = let y = x in y