version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
