-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Nat as ℕ using (ℕ)
open import Data.Fin as Fin using (Fin; #_)
open import Data.List

module simple-matrix-temp-output where

postulate t : Tensor ℕ (2 ∷ (2 ∷ []))

expandedExpr2 : ℕ
expandedExpr2 = t (# 0) (# 1)