{-# OPTIONS_GHC -Wno-orphans #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

{-# HLINT ignore "Use <$>" #-}

module Vehicle.Compile.Print.Warning where

import Data.Bifunctor (Bifunctor (..))
import Data.List.NonEmpty (NonEmpty, sort)
import Data.List.NonEmpty qualified as NonEmpty
import Data.Map qualified as Map
import Data.Maybe (fromMaybe)
import Data.Set qualified as Set
import Data.Tuple (swap)
import Vehicle.Data.Tensor (TensorIndices)
import Vehicle.Prelude
import Vehicle.Prelude.Warning
import Vehicle.Verify.Core

instance Pretty SummarisedCompileWarning where
  pretty = \case
    UnusedResourcesSummary resourceType unusedResources ->
      "the following"
        <+> pretty resourceType
        <> "s were provided"
          <+> "but not used by the specification:"
          <+> prettySet pretty unusedResources
    TrivialPropertySummary propertyName status ->
      "The property"
        <+> quotePretty propertyName
        <+> "was found to evaluate to"
        <+> quotePretty status
        <+> "without needing to call the solver. This usually indicates a fault with either the"
        <+> "specification or any external datasets used."
    UnderSpecifiedProblemSpaceVariablesSummary propertyName unsolvedVars -> do
      "In property"
        <+> quotePretty propertyName
        <+> "there are quantified variables that not always directly related to the input or output of a network."
        <+> "This is frequently indicative of a bug in the specification. These variables are:"
        <> line
        <> prettyObjectsAndTensorIndicesList prettyVariables propertyName unsolvedVars
    UnsoundStrictOrderConversionsSummary queryFormatID propertyAddress _ ->
      "In property"
        <+> quotePretty propertyAddress
        <> ", at least one of the generated queries were found"
          <+> "to contain a strict inequality (i.e. constraints of the form 'x < y')."
          <+> "Unfortunately the"
          <+> pretty queryFormatID
          <+> "only supports non-strict"
          <+> "inequalities (i.e. constraints of the form 'x <= y')."
        <> line
        <> line
        <> "In order to provide support, Vehicle has automatically converted the"
          <+> "strict inequalities to non-strict inequalites."
          <+> "This is not sound, but errors will be at most the floating point epsilon"
          <+> "used by the solver, which is usually very small (e.g. 1e-9)."
          <+> "However, this may lead to unexpected behaviour (e.g. loss of the law of excluded middle)."
        <> line
        <> line
        <> "See https://github.com/vehicle-lang/vehicle/issues/74 for further details."
    AllConstantNetworkInputVariablesSummary _ propertyName indices ->
      "In some of the queries generated by property"
        <+> quotePretty propertyName
        <> fromMaybe "" (prettyTensorIndices propertyName indices)
          <+> "all network inputs were fixed to be constants."
          <+> "Unfortunately there is a known bug in Marabou that it sometimes erroneously returns"
          <+> "'unsat' for these type of queries."
        <> line
        <> line
        <> "See https://github.com/NeuralNetworkVerification/Marabou/issues/670 for details."
    BoundsOnlyQuantifierSummary propertyName quantifierName ->
      "In some cases in"
        <+> pretty AnnProperty
        <+> quotePretty propertyName
        <+> "the constraints on quantified variable"
        <+> quotePretty quantifierName
        <+> "consist only of direct bounds, and"
        <+> quotePretty quantifierName
        <+> "is not related to a"
        <+> pretty NetworkDef
        <+> "declaration in any way."

prettyObjects :: (Ord a, Pretty a) => Bool -> Doc b -> Doc b -> NonEmpty a -> Doc b
prettyObjects shouldQuote single plural ids =
  (if length ids == 1 then single else plural)
    <+> prettyNonEmptyList (fmap (if shouldQuote then quotePretty else pretty) (sort ids))

prettyQueryIDs :: NonEmpty QueryID -> Doc b
prettyQueryIDs = prettyObjects False "query" "queries"

prettyVariables :: NonEmpty Name -> Doc a
prettyVariables = prettyObjects True "variable" "variables"

prettyTensorIndices :: PropertyName -> NonEmpty TensorIndices -> Maybe (Doc b)
prettyTensorIndices name indices = do
  let uniqueIndices = Set.toList $ Set.fromList $ NonEmpty.toList indices
  if uniqueIndices == [[]]
    then Nothing
    else do
      let addresses = fmap (quotePretty . PropertyAddress name) indices
      Just $ prettyNonEmptyList addresses

prettyObjectsAndTensorIndices :: (NonEmpty a -> Doc b) -> PropertyName -> (NonEmpty a, NonEmpty TensorIndices) -> Doc b
prettyObjectsAndTensorIndices prettyObject name (ids, indices) = do
  let indicesDoc = prettyTensorIndices name indices
  prettyObject ids <> maybe "" (" in" <+>) indicesDoc

prettyObjectsAndTensorIndicesList :: (Ord a) => (NonEmpty a -> Doc b) -> PropertyName -> NonEmpty (a, TensorIndices) -> Doc b
prettyObjectsAndTensorIndicesList prettyObject name objectsAndIndices = do
  -- Singleton.nonEmpty doesn't exist until base 4.15
  let nonEmptySingleton x = [x]
  -- First map by indices that share the same objects
  let indicesMap = Map.fromListWith (<>) (NonEmpty.toList $ fmap (second nonEmptySingleton) objectsAndIndices)
  -- Then find the objects that share the same queries
  let objectsMap = Map.fromListWith (<>) $ fmap (second nonEmptySingleton . swap) (Map.toList indicesMap)
  let finalGroups = fmap swap $ Map.toList objectsMap
  indent 2 (vsep (fmap (\x -> "-" <+> prettyObjectsAndTensorIndices prettyObject name x) finalGroups))
