"""Train a small MLP against the DL2 loss for the windController.vcl spec.

The Input and Output classes are generated by

    vehicle compile python-types -s windController.vcl -o windController_types.py

and the IDE shows shape-typed fields on them. Run from this directory:

    uv run python train.py
"""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.optim as optim
import windController_types
from vehicle_lang.loss.pytorch import load_specification
from windController_types import Input, Output

SPEC_PATH = "windController.vcl"


class Controller(nn.Module):
    def __init__(self, hidden: int = 16) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, hidden),
            nn.Tanh(),
            nn.Linear(hidden, 1),
        )

    def forward(self, x: Input) -> Output:
        flat = torch.stack([x.currentSensor, x.previousSensor], dim=-1)
        return Output(deltaVelocity=self.net(flat).squeeze(-1))


if __name__ == "__main__":
    spec = load_specification(SPEC_PATH, types=windController_types)
    safe = spec["safe"]

    torch.manual_seed(0)
    controller = Controller()

    sample = Input(
        currentSensor=torch.tensor(0.5),
        previousSensor=torch.tensor(-0.3),
    )
    print(f"sample input:  {sample}")
    print(f"controller out: {controller(sample)}")

    optimiser = optim.Adam(controller.parameters(), lr=1e-2)
    for step in range(50):
        optimiser.zero_grad()
        loss = safe(controller).mean()
        loss.backward()
        optimiser.step()
        if step % 10 == 0:
            print(f"step {step:3d}  loss={loss.item():.6f}")

    final = safe(controller).mean().item()
    print(f"final loss: {final:.6f}")
