"""Auto-generated by vehicle-lang from windController.vcl. Do not edit."""

from __future__ import annotations

from dataclasses import dataclass

from jaxtyping import Float
from torch import Tensor


@dataclass(frozen=True)
class Input:
    currentSensor: Float[Tensor, ""]
    previousSensor: Float[Tensor, ""]


@dataclass(frozen=True)
class Output:
    deltaVelocity: Float[Tensor, ""]
