-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Integer as ℤ using (ℤ)
open import Data.Rational as ℚ using (ℚ)
open import Data.Bool as 𝔹 using (Bool; true; false; if_then_else_)
open import Data.Fin as Fin using (#_)
open import Data.List
open import Relation.Nullary
open import Relation.Nullary.Decidable

module windController-output where

private
  VEHICLE_PROJECT_FILE = "TODO_projectFile"

InputVector : Set
InputVector = Tensor ℚ (2 ∷ [])

deltaV : InputVector → ℚ
deltaV = evaluate record
  { projectFile = VEHICLE_PROJECT_FILE
  ; networkUUID = "TODO_networkUUID"
  }

abs : ℚ → ℚ
abs x = if ⌊ x ℚ.<? ℤ.+ 0 ℚ./ 1 ⌋ then ℚ.- x else x

currentPosition : InputVector → ℚ
currentPosition x = x (# 0)

prevPosition : InputVector → ℚ
prevPosition x = x (# 1)

SafeInput : InputVector → Set
SafeInput x = abs (currentPosition x) ℚ.< ℤ.+ 3 ℚ./ 1

SafeOutput : InputVector → Set
SafeOutput x = abs ((deltaV x ℚ.+ (ℤ.+ 2 ℚ./ 1) ℚ.* currentPosition x) ℚ.- prevPosition x) ℚ.< ℤ.+ 2 ℚ./ 1

abstract
  safe : ∀ (x : Tensor ℚ (2 ∷ [])) → SafeInput x → SafeOutput x
  safe = checkProperty record
    { projectFile  = VEHICLE_PROJECT_FILE
    ; propertyUUID = "TODO_propertyUUID"
    }