-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Product
open import Data.Integer as ℤ using (ℤ)
open import Data.Rational as ℚ using (ℚ)
open import Data.Fin as Fin using (#_)
open import Data.List

module windController-output where

private
  VEHICLE_PROJECT_FILE = "TODO_projectFile"

InputVector : Set
InputVector = Tensor ℚ (2 ∷ [])

deltaV : InputVector → ℚ
deltaV = evaluate record
  { projectFile = VEHICLE_PROJECT_FILE
  ; networkUUID = "TODO_networkUUID"
  }

currPosition : InputVector → ℚ
currPosition x = x (# 0)

prevPosition : InputVector → ℚ
prevPosition x = x (# 1)

SafeInput : InputVector → Set
SafeInput x = (ℚ.- (ℤ.+ 13 ℚ./ 4) ℚ.≤ currPosition x × currPosition x ℚ.≤ ℤ.+ 13 ℚ./ 4) × (ℚ.- (ℤ.+ 13 ℚ./ 4) ℚ.≤ prevPosition x × prevPosition x ℚ.≤ ℤ.+ 13 ℚ./ 4)

SafeOutput : InputVector → Set
SafeOutput x = ℚ.- (ℤ.+ 5 ℚ./ 4) ℚ.< (deltaV x ℚ.+ (ℤ.+ 2 ℚ./ 1) ℚ.* currPosition x) ℚ.- prevPosition x × (deltaV x ℚ.+ (ℤ.+ 2 ℚ./ 1) ℚ.* currPosition x) ℚ.- prevPosition x ℚ.< ℤ.+ 5 ℚ./ 4

abstract
  safe : ∀ (x : Tensor ℚ (2 ∷ [])) → SafeInput x → SafeOutput x
  safe = checkProperty record
    { projectFile  = VEHICLE_PROJECT_FILE
    ; propertyUUID = "TODO_propertyUUID"
    }