"""Build @tensor record classes, as runtime types or as source for a typed module."""

from __future__ import annotations

import hashlib
import io
import json
import math
from pathlib import Path
from types import ModuleType
from typing import Any, Sequence, TextIO

from .._ast import _nodes as vcl
from ..error import VehicleInternalError

DIGEST_ATTR = "__vehicle_schema_digest__"


def schemas_of(program: vcl.Program) -> list[vcl.DefRecordSchema]:
    assert isinstance(program, vcl.Main)
    return [d for d in program.declarations if isinstance(d, vcl.DefRecordSchema)]


def schema_digest(schemas: Sequence[vcl.DefRecordSchema]) -> str:
    canonical = json.dumps(
        [
            [s.name, [[fname, _field_repr(ftype)] for fname, ftype in s.fields]]
            for s in schemas
        ],
        separators=(",", ":"),
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def render_module(schemas: Sequence[vcl.DefRecordSchema], spec_name: str) -> str:
    buf = io.StringIO()
    _emit_module(buf, spec_name, list(schemas))
    return buf.getvalue()


def build_record_classes(
    schemas: Sequence[vcl.DefRecordSchema], spec_path: str | Path
) -> ModuleType:
    spec_name = Path(spec_path).name
    source = render_module(schemas, spec_name)
    module = ModuleType(f"vehicle_lang.loss.records.{Path(spec_name).stem}")
    module.__file__ = f"<vehicle records from {spec_name}>"
    exec(compile(source, module.__file__, "exec"), module.__dict__)
    return module


def _field_repr(ftype: vcl.FieldType) -> list[Any]:
    match ftype:
        case vcl.FieldScalarReal():
            return ["scalar"]
        case vcl.FieldTensorReal(shape):
            return ["tensor", list(shape)]
        case vcl.FieldRecordRef(ref):
            return ["ref", ref]
        case _:
            raise NotImplementedError(f"unsupported FieldType: {type(ftype).__name__}")


def _quoted_tuple(names: list[str]) -> str:
    inner = ", ".join(f'"{n}"' for n in names)
    if len(names) == 1:
        return f"({inner},)"
    return f"({inner})"


def _emit_module(
    out: TextIO, spec_name: str, schemas: list[vcl.DefRecordSchema]
) -> None:
    out.write(f'"""Auto-generated by vehicle-lang from {spec_name}. Do not edit."""\n')
    out.write("\n")
    out.write("from __future__ import annotations\n")
    out.write("\n")
    out.write("import torch\n")
    out.write("from jaxtyping import Float\n")
    out.write("from torch import Tensor\n")
    out.write("\n")
    out.write(f'{DIGEST_ATTR} = "{schema_digest(schemas)}"\n')
    widths: dict[str, int] = {}
    for schema in schemas:
        _emit_schema(out, schema, widths)


def _emit_schema(
    out: TextIO, schema: vcl.DefRecordSchema, widths: dict[str, int]
) -> None:
    name = schema.name
    field_names: list[str] = [fname for fname, _ in schema.fields]
    field_widths: list[int] = [_flat_width(ftype, widths) for _, ftype in schema.fields]
    offsets: list[int] = []
    acc = 0
    for w in field_widths:
        offsets.append(acc)
        acc += w
    total = acc
    widths[name] = total

    out.write("\n\n")
    out.write(f"class {name}(torch.Tensor):  # type: ignore[misc]\n")
    out.write("    # Make torch.* ops return plain Tensor, not this subclass.\n")
    out.write("    __torch_function__ = torch._C._disabled_torch_function_impl\n")
    out.write("\n")
    out.write(f"    _FIELDS: tuple[str, ...] = {_quoted_tuple(field_names)}\n")
    out.write(f"    _FLAT_WIDTH: int = {total}\n")
    out.write("    _FIELD_SLOTS: dict[str, tuple[int, int]] = {\n")
    for fname, off, w in zip(field_names, offsets, field_widths):
        out.write(f'        "{fname}": ({off}, {off + w}),\n')
    out.write("    }\n")
    out.write("\n")

    out.write("    @staticmethod\n")
    out.write(
        f'    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> "{name}":\n'
    )
    out.write("        if _from_tensor is not None:\n")
    out.write(
        "            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]\n"
    )
    out.write("        slabs = []\n")
    for fname, ftype in schema.fields:
        match ftype:
            case vcl.FieldScalarReal():
                out.write(f'        v_{fname} = torch.as_tensor(fields["{fname}"])\n')
                out.write(
                    f"        slabs.append(v_{fname}.reshape(*v_{fname}.shape, 1))\n"
                )
            case vcl.FieldTensorReal(shape):
                out.write(f'        v_{fname} = torch.as_tensor(fields["{fname}"])\n')
                width = _prod_shape(shape)
                out.write(
                    f"        slabs.append(v_{fname}.reshape(*v_{fname}.shape[:-{len(shape)}], {width}))\n"
                )
            case vcl.FieldRecordRef(_):
                out.write(f'        v_{fname} = fields["{fname}"]\n')
                out.write(
                    f"        slabs.append(v_{fname}.as_subclass(torch.Tensor))\n"
                )
    out.write(
        "        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]\n"
    )
    out.write("\n")

    out.write("    @classmethod\n")
    out.write(f'    def from_tensor(cls, t: Tensor) -> "{name}":\n')
    out.write("        return t.as_subclass(cls)  # type: ignore[no-any-return]\n")
    out.write("\n")
    out.write("    def to_tensor(self) -> Tensor:\n")
    out.write("        return self.as_subclass(torch.Tensor)\n")

    for fname, ftype in schema.fields:
        out.write("\n")
        out.write("    @property\n")
        out.write(f"    def {fname}(self) -> {_field_annotation(ftype)}:\n")
        out.write(f'        lo, hi = {name}._FIELD_SLOTS["{fname}"]\n')
        out.write("        base = self.as_subclass(torch.Tensor)[..., lo:hi]\n")
        match ftype:
            case vcl.FieldScalarReal():
                out.write("        return base.reshape(self.shape[:-1])\n")
            case vcl.FieldTensorReal(shape):
                shape_tuple = tuple(shape)
                out.write(
                    f"        return base.reshape((*self.shape[:-1], *{shape_tuple!r}))\n"
                )
            case vcl.FieldRecordRef(ref):
                out.write(f"        return {ref}.from_tensor(base)\n")


def _flat_width(ftype: vcl.FieldType, widths: dict[str, int]) -> int:
    match ftype:
        case vcl.FieldScalarReal():
            return 1
        case vcl.FieldTensorReal(shape):
            return _prod_shape(shape)
        case vcl.FieldRecordRef(ref):
            if ref not in widths:
                raise VehicleInternalError(
                    f"record schema {ref!r} referenced before definition; "
                    f"schemas must be emitted in topological order"
                )
            return widths[ref]
        case _:
            raise NotImplementedError(f"unsupported FieldType: {type(ftype).__name__}")


def _prod_shape(shape: Sequence[int | str]) -> int:
    concrete: list[int] = []
    for d in shape:
        if isinstance(d, int):
            concrete.append(d)
        else:
            raise NotImplementedError(f"symbolic dim {d!r} in @tensor record field")
    return math.prod(concrete) if concrete else 1


def _field_annotation(ftype: vcl.FieldType) -> str:
    match ftype:
        case vcl.FieldScalarReal():
            return 'Float[Tensor, ""]'
        case vcl.FieldTensorReal(shape):
            return f'Float[Tensor, "{" ".join(str(d) for d in shape)}"]'
        case vcl.FieldRecordRef(schema):
            return schema
        case _:
            raise NotImplementedError(f"unsupported FieldType: {type(ftype).__name__}")
