"""Emit a typed Python module from a spec's @tensor record schemas."""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import TextIO

from .._ast import _nodes as vcl
from ..typing import DifferentiableLogic
from . import load_ast


def generate(
    spec_path: str | Path,
    output: TextIO | Path,
    *,
    logic: DifferentiableLogic = DifferentiableLogic.DL2,
) -> None:
    """Read 'spec_path' and emit @dataclass definitions for each @tensor record schema."""
    program = load_ast(spec_path, target=logic)
    if not isinstance(program, vcl.Main):
        raise RuntimeError(
            f"unexpected Program shape from {spec_path}: {type(program).__name__}"
        )
    schemas = [d for d in program.declarations if isinstance(d, vcl.DefRecordSchema)]

    buf = io.StringIO()
    _emit_module(buf, Path(str(spec_path)).name, schemas)
    text = buf.getvalue()

    if isinstance(output, (str, Path)):
        Path(output).write_text(text)
    else:
        output.write(text)


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="vehicle compile python-types",
        description="Emit a typed Python module with @dataclass definitions for each @tensor record in the spec.",
    )
    parser.add_argument(
        "-s", "--specification", required=True, help="path to the .vcl spec"
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="path to the output .py file, or '-' for stdout",
    )
    parser.add_argument(
        "--logic",
        default="DL2",
        help="differentiable logic used to load the spec (default: DL2)",
    )
    args = parser.parse_args()

    logic = DifferentiableLogic[args.logic]
    if args.output == "-":
        generate(args.specification, sys.stdout, logic=logic)
    else:
        generate(args.specification, Path(args.output), logic=logic)
    return 0


# Emission helpers -------------------------------------------------------------


def _emit_module(
    out: TextIO, spec_name: str, schemas: list[vcl.DefRecordSchema]
) -> None:
    out.write(f'"""Auto-generated by vehicle-lang from {spec_name}. Do not edit."""\n')
    out.write("\n")
    out.write("from __future__ import annotations\n")
    out.write("\n")
    out.write("from dataclasses import dataclass\n")
    out.write("\n")
    out.write("from jaxtyping import Float\n")
    out.write("from torch import Tensor\n")
    for schema in schemas:
        out.write("\n\n")
        out.write("@dataclass(frozen=True)\n")
        out.write(f"class {schema.name}:\n")
        for fname, ftype in schema.fields:
            out.write(f"    {fname}: {_field_annotation(ftype)}\n")


def _field_annotation(ftype: vcl.FieldType) -> str:
    match ftype:
        case vcl.JFieldScalarReal():
            return 'Float[Tensor, ""]'
        case vcl.JFieldTensorReal(shape):
            return f'Float[Tensor, "{" ".join(str(d) for d in shape)}"]'
        case vcl.JFieldRecordRef(schema):
            return schema
        case _:
            raise NotImplementedError(f"unsupported FieldType: {type(ftype).__name__}")


if __name__ == "__main__":
    sys.exit(main())
