-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Rational as ℚ using (ℚ)
open import Data.List
open import Relation.Binary.PropositionalEquality

module autoencoderError-temp-output where

postulate encode : Tensor ℚ (5 ∷ []) → Tensor ℚ (2 ∷ [])

postulate decode : Tensor ℚ (2 ∷ []) → Tensor ℚ (5 ∷ [])

abstract
  identity : ∀ (x : Tensor ℚ (5 ∷ [])) → decode (encode x) ≡ x
  identity = checkProperty record
    { proofCache   = "/home/matthew/Code/AISEC/vehicle/proofcache.vclp"
    }