-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

open import AISEC.Utils
open import Data.Product
open import Data.Sum
open import Data.Nat as ℕ using (ℕ)
open import Data.Rational as ℚ using (ℚ)
open import Data.Real as ℝ using (ℝ)
open import Data.List
open import Data.List.Relation.Unary.All as List

module MyTestModule where

pi : ℝ
pi = 392699 ℚ./ 125000

InputVector : Set
InputVector = Tensor ℝ (5 ∷ [])

OutputVector : Set
OutputVector = Tensor ℝ (5 ∷ [])

acasXu : InputVector → OutputVector
acasXu = evaluate record
  { databasePath = DATABASE_PATH
  ; networkUUID  = NETWORK_UUID
  }

distanceToIntruder : InputVector → ℝ
distanceToIntruder x = x 0

angleToIntruder : InputVector → ℝ
angleToIntruder x = x 1

intruderHeading : InputVector → ℝ
intruderHeading x = x 2

speed : InputVector → ℝ
speed x = x 3

intruderSpeed : InputVector → ℝ
intruderSpeed x = x 4

clearOfConflictScore : InputVector → ℝ
clearOfConflictScore x = acasXu x 0

intruderFarAway : InputVector → Set
intruderFarAway x = (ℤ.- pi ℝ.≤ angleToIntruder x × angleToIntruder x ℝ.≤ ℤ.- (7 ℚ./ 10) ⊎ 7 ℚ./ 10 ℝ.≤ angleToIntruder x × angleToIntruder x ℝ.≤ pi) × (12000 ℝ.≤ distanceToIntruder x × (distanceToIntruder x ℝ.≤ 62000 × (ℤ.- pi ℝ.≤ intruderHeading x × (intruderHeading x ℝ.≤ ℤ.- pi ℝ.+ 1 ℚ./ 200 × (100 ℝ.≤ speed x × (speed x ℝ.≤ 1200 × (0 ℝ.≤ intruderSpeed x × intruderSpeed x ℝ.≤ 1200)))))))

advisesClearOfConflict : InputVector → Set
advisesClearOfConflict x = let y = acasXu x in List.All (λ (i : ℕ) → y 0 ℝ.≥ y i) (0 ∷ (1 ∷ (2 ∷ (3 ∷ (4 ∷ [])))) : List ℕ)

property6 : ∀ (x : Tensor ℝ (5 ∷ [])) → intruderFarAway x → advisesClearOfConflict x
property6 = checkProperty record
  { databasePath = DATABASE_PATH
  ; propertyUUID = ????
  }