-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

open import AISEC.Utils
open import Data.Product
open import Data.Nat as ℕ using (ℕ)
open import Data.Rational as ℚ using (ℚ)
open import Data.Real as ℝ using (ℝ)
open import Data.List
open import Data.List.Relation.Unary.All as List

module MyTestModule where

private
  VEHICLE_PROJECT_FILE = TODO/vehicle/path

andGate : Tensor ℝ (2 ∷ []) → Tensor ℝ (1 ∷ [])
andGate = evaluate record
  { projectFile = VEHICLE_PROJECT_FILE
  ; networkUUID = NETWORK_UUID
  }

truthy : ℝ → Set
truthy x = x ℝ.≥ 1 ℚ./ 2

falsey : ℝ → Set
falsey x = x ℝ.≤ 1 ℚ./ 2

validInput : Tensor ℝ (2 ∷ []) → Set
validInput x = List.All (λ (i : ℕ) → 0 ℝ.≤ x i × x i ℝ.≤ 1) (0 ∷ (1 ∷ []) : List ℕ)

correctOutput : Tensor ℝ (2 ∷ []) → Set
correctOutput x = let y = andGate x in (truthy x 0 × truthy x 1 → truthy y 0) × ((truthy x 0 × falsey x 1 → falsey y 0) × ((falsey x 0 × truthy x 1 → falsey y 0) × (falsey x 0 × falsey x 1 → falsey y 0)))

abstract
  correct : ∀ (x : Tensor ℝ (2 ∷ [])) → validInput x → correctOutput x
  correct = checkProperty record
    { projectFile  = VEHICLE_PROJECT_FILE
    ; propertyUUID = ????
    }