-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Data.Nat as ℕ using (ℕ)

module simple-generalisedVariables-temp-output where

id : ∀ {a : Set} (_x0 : a) → a
id x = x

natId : ℕ → ℕ
natId = id