-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Rational as ℚ using (ℚ)
open import Data.List
open import Relation.Binary.PropositionalEquality

module autoencoderError-output where

private
  VEHICLE_PROJECT_FILE = "TODO_projectFile"

encode : Tensor ℚ (1 ∷ []) → Tensor ℚ (1 ∷ [])
encode = evaluate record
  { projectFile = VEHICLE_PROJECT_FILE
  ; networkUUID = "TODO_networkUUID"
  }

decode : Tensor ℚ (1 ∷ []) → Tensor ℚ (1 ∷ [])
decode = evaluate record
  { projectFile = VEHICLE_PROJECT_FILE
  ; networkUUID = "TODO_networkUUID"
  }

abstract
  identity : ∀ (x : Tensor ℚ (1 ∷ [])) → decode (encode x) ≡ x
  identity = checkProperty record
    { projectFile  = VEHICLE_PROJECT_FILE
    ; propertyUUID = "TODO_propertyUUID"
    }