-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Data.Fin as Fin using (Fin; #_)
open import Function.Base
open import Relation.Binary.PropositionalEquality

module simple-index-output where

eqIndex : Set
eqIndex = (Fin 1 ∋ # 0) ≡ (Fin 2 ∋ # 1)

neqIndex : Set
neqIndex = (Fin 1 ∋ # 0) ≢ (Fin 2 ∋ # 1)

leqIndex : Set
leqIndex = (Fin 1 ∋ # 0) Fin.≤ (Fin 2 ∋ # 1)

ltIndex : Set
ltIndex = (Fin 1 ∋ # 0) Fin.< (Fin 2 ∋ # 1)

geqIndex : Set
geqIndex = (Fin 1 ∋ # 0) Fin.≥ (Fin 2 ∋ # 1)

gtIndex : Set
gtIndex = (Fin 1 ∋ # 0) Fin.> (Fin 2 ∋ # 1)
