"""Auto-generated by vehicle-lang from dice-record.vcl. Do not edit."""



from __future__ import annotations



import torch



from jaxtyping import Float

from torch import Tensor





class Image(torch.Tensor):  # type: ignore[misc]

    # Make torch.* ops return plain Tensor, not this subclass.

    __torch_function__ = torch._C._disabled_torch_function_impl



    _FIELDS: tuple[str, ...] = ('r', 'g', 'b')

    _FLAT_WIDTH: int = 2352

    _FIELD_SLOTS: dict[str, tuple[int, int]] = {

        'r': (0, 784),

        'g': (784, 1568),

        'b': (1568, 2352),

    }



    @staticmethod

    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> 'Image':

        if _from_tensor is not None:

            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]

        slabs = []

        v_r = torch.as_tensor(fields['r'])

        slabs.append(v_r.reshape(*v_r.shape[:-2], 784))

        v_g = torch.as_tensor(fields['g'])

        slabs.append(v_g.reshape(*v_g.shape[:-2], 784))

        v_b = torch.as_tensor(fields['b'])

        slabs.append(v_b.reshape(*v_b.shape[:-2], 784))

        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]



    @classmethod

    def from_tensor(cls, t: Tensor) -> 'Image':

        return t.as_subclass(cls)  # type: ignore[no-any-return]



    def to_tensor(self) -> Tensor:

        return self.as_subclass(torch.Tensor)



    @property

    def r(self) -> Float[Tensor, "28 28"]:

        lo, hi = Image._FIELD_SLOTS['r']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape((*self.shape[:-1], *(28, 28)))



    @property

    def g(self) -> Float[Tensor, "28 28"]:

        lo, hi = Image._FIELD_SLOTS['g']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape((*self.shape[:-1], *(28, 28)))



    @property

    def b(self) -> Float[Tensor, "28 28"]:

        lo, hi = Image._FIELD_SLOTS['b']

        base = self.as_subclass(torch.Tensor)[..., lo:hi]

        return base.reshape((*self.shape[:-1], *(28, 28)))