(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Isabelle version: 2024 *)
(*  - Vehicle version: 0.21.0+dev *)

theory  WindControllerSpec

  imports

    "Complex_Main"

    "Deep_Learning.Tensor"
    "Vehicle"

begin

  type_synonym R = "real"

  typedef InputVector  =  "{ a :: R tensor. (dims a) = ((2 :: nat) # []) }"
    using dims_tensor_from_lookup by blast
  typedef OutputVector  =  "{ a :: R tensor. (dims a) = ((1 :: nat) # []) }"
    using dims_tensor_from_lookup by blast

  

  definition currentSensor  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow>  nat "
    where " currentSensor   controller = 0 "

  definition previousSensor  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow>  nat "
    where " previousSensor   controller = 1 "



  definition velocity  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow>  nat "
    where " velocity   controller = 0 "



  definition normalise  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  InputVector "
    where " normalise   controller x = nstack (fun i => (lookup x [i]) + const_t (4 : R) / const_t (8 : R)) "

  definition safeInput  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  Prop "
    where " safeInput   controller x = forallIndex (fun i => (- const_t (13 / 4 : R) <= (lookup x [i])) /\ ((lookup x [i]) <= const_t (13 / 4 : R))) "

  definition safeOutput  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  Prop "
    where " safeOutput   controller x = let y := (lookup (controller (normalise x)) [velocity]) in (- const_t (5 / 4 : R) < ((y + (const_t (2 : R) * (lookup x [currentSensor]))) - (lookup x [previousSensor]))) /\ (((y + (const_t (2 : R) * (lookup x [currentSensor]))) - (lookup x [previousSensor])) < const_t (5 / 4 : R)) "



  locale  WindControllerSpec  = 

    fixes  controller  :: " InputVector \<Rightarrow> OutputVector "

    assumes  safe :  " forall x, safeInput x -> safeOutput x "

    begin

    end

end