(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Isabelle version: 2024 *)
(*  - Vehicle version: 0.21.0+dev *)

theory  WindControllerSpec

  imports

    "Complex_Main"

    "Deep_Learning.Tensor"
    "Deep_Learning.Tensor_Subtensor"
    "Deep_Learning.Tensor_Scalar_Mult"
    "Vehicle.Vehicle"

begin

  type_synonym R = "real"

  typedef InputVector  =  "{ a :: R tensor. (dims a) = ((2 :: nat) # []) }"
    using dims_tensor_from_lookup by blast
  declare [[coercion Rep_InputVector]]
  definition to_InputVector :: "R FlexTensor ⇒ InputVector"
    where[simp]: "to_InputVector a =
      (let t = Rep_FlexTensor a
       in if dims t = ((2 :: nat) # []) then Abs_InputVector t else undefined)"
  declare [[coercion to_InputVector]]
  typedef OutputVector  =  "{ a :: R tensor. (dims a) = ((1 :: nat) # []) }"
    using dims_tensor_from_lookup by blast
  declare [[coercion Rep_OutputVector]]
  definition to_OutputVector :: "R FlexTensor ⇒ OutputVector"
    where[simp]: "to_OutputVector a =
      (let t = Rep_FlexTensor a
       in if dims t = ((1 :: nat) # []) then Abs_OutputVector t else undefined)"
  declare [[coercion to_OutputVector]]

  

  definition currentSensor  :: "  nat "
    where " currentSensor   = ( 0 ) "

  definition previousSensor  :: "  nat "
    where " previousSensor   = ( 1 ) "



  definition velocity  :: "  nat "
    where " velocity   = ( 0 ) "



  definition normalise  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  InputVector "
    where " normalise   controller x = ( (foreach (2 :: nat)  (\<lambda>  i . ((pointwise_div (tensor_plus (subtensor_lookup x i) (tensor_from_vec [1] [ (((4 :: R) )) ])) (tensor_from_vec [1] [ (((8 :: R) )) ]))))) ) "

  definition safeInput  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  bool "
    where " safeInput   controller x = ( (forallIndex (2 :: nat)  (\<lambda>  i . ((leqTensorReduced ((-1 :: R) \<cdot> (tensor_from_vec [1] [ (((13 :: R) / 4)) ])) (subtensor_lookup x i)) \<and> (leqTensorReduced (subtensor_lookup x i) (tensor_from_vec [1] [ (((13 :: R) / 4)) ]))))) ) "

  definition safeOutput  :: " (InputVector \<Rightarrow> OutputVector) \<Rightarrow> (InputVector) \<Rightarrow>  bool "
    where " safeOutput   controller x = ( let y = (subtensor_lookup ((controller ((normalise controller x)))) velocity) in (ltTensorReduced ((-1 :: R) \<cdot> (tensor_from_vec [1] [ (((5 :: R) / 4)) ])) ((tensor_plus ((tensor_plus y ((hadamard_prod (tensor_from_vec [1] [ (((2 :: R) )) ]) (subtensor_lookup x currentSensor))))) ((-1 :: R) \<cdot> (subtensor_lookup x previousSensor))))) \<and> (ltTensorReduced ((tensor_plus ((tensor_plus y ((hadamard_prod (tensor_from_vec [1] [ (((2 :: R) )) ]) (subtensor_lookup x currentSensor))))) ((-1 :: R) \<cdot> (subtensor_lookup x previousSensor)))) (tensor_from_vec [1] [ (((5 :: R) / 4)) ])) ) "



  locale  WindControllerSpec  = 

    fixes  controller  :: " InputVector \<Rightarrow> OutputVector "

    assumes  safe :  " \<forall> x. (safeInput controller x) \<longrightarrow> (safeOutput controller x) "

    begin

    end

end