module Vehicle.Compile.FourierMotzkinElimination
  ( fourierMotzkinElimination,
    reconstructFourierMotzkinVariableValue,
  )
where

import Data.List.NonEmpty (NonEmpty (..))
import Data.Map (Map)
import Vehicle.Compile.Error
import Vehicle.Compile.Prelude
import Vehicle.Compile.Print
import Vehicle.Data.Assertion
import Vehicle.Data.Bound
import Vehicle.Data.Bound.Operations (andBoundList)
import Vehicle.Data.Code.BooleanExpr (ConjunctAll (..), eliminateTrivialConjunctions)
import Vehicle.Data.Code.Interface (mkDims)
import Vehicle.Data.Code.LinearExpr
import Vehicle.Data.MaybeTrivial (MaybeTrivial (..))
import Vehicle.Data.Tensor (RatTensor, mapTensor, zipWithTensor, pattern ZeroDimTensor)
import Vehicle.Data.Variable.Bound.Context.Name (MonadNameContext)
import Vehicle.Data.Variable.Bound.Level
import Vehicle.Prelude.Logging (runSilentLogger)

-- | TODO If performance proves unnacceptably poor look into
-- Imbert's acceleration theorems:
--
-- Jean-Louis Imbert,
-- About Redundant Inequalities Generated by Fourier's Algorithm
-- Artificial Intelligence IV: Methodology, Systems, Applications, 1990
fourierMotzkinElimination ::
  (MonadCompile m, MonadNameContext m, ConstantLike constant, PrettyFriendly (constant `In` NamedBoundCtx)) =>
  SliceVariable ->
  [Inequality (LinearExpr SliceVariable constant)] ->
  m (Bounds (LinearExpr SliceVariable constant), MaybeTrivial (ConjunctAll (Inequality (LinearExpr SliceVariable constant))))
fourierMotzkinElimination var inequalities = do
  let (solution@(Bounds lower upper), unusedInequalities) = partition var inequalities

  let newMaybeTrivialInequalities = cartesianProduct combineInequalities lower upper
  let allMaybeTrivialInequalities = newMaybeTrivialInequalities <> fmap NonTrivial unusedInequalities
  let maybeTrivialFinalInequalities = case allMaybeTrivialInequalities of
        [] -> Trivial True
        x : xs -> eliminateTrivialConjunctions (ConjunctAll (x :| xs))

  return (solution, maybeTrivialFinalInequalities)

combineInequalities ::
  (VariableLike variable, ConstantLike constant) =>
  LowerBound (LinearExpr variable constant) ->
  UpperBound (LinearExpr variable constant) ->
  MaybeTrivial (Inequality (LinearExpr variable constant))
combineInequalities (LowerBound rel1 lowerBound) (UpperBound rel2 upperBound) = do
  let maybeNewExpr = addExprs 1 (-1) lowerBound upperBound
  let newRel = combineInequalityRelations rel1 rel2
  case maybeNewExpr of
    Left constant -> Trivial $ evalTrivialRelation newRel constant
    Right newExpr -> NonTrivial $ NormalisedRelation newRel newExpr

-- | Partitions the inequalities into three sets:
--  1. Those where the rest of the expression is less than the variable
--  2. Those where the rest of the expression is greater than the variable
--  3. Those which don't mention the variable at all.
partition ::
  forall variable constant.
  (VariableLike variable, ConstantLike constant) =>
  variable ->
  [Inequality (LinearExpr variable constant)] ->
  (Bounds (LinearExpr variable constant), [Inequality (LinearExpr variable constant)])
partition var = foldr categorise (Bounds [] [], [])
  where
    categorise ::
      (ConstantLike constant) =>
      Inequality (LinearExpr variable constant) ->
      (Bounds (LinearExpr variable constant), [Inequality (LinearExpr variable constant)]) ->
      (Bounds (LinearExpr variable constant), [Inequality (LinearExpr variable constant)])
    categorise ineq@(NormalisedRelation rel expr) (bounds@Bounds {..}, unused) = do
      let (coeff, valueExpr) = rearrangeExprToSolveFor var expr
      if coeff < 0
        then (Bounds {lowerBounds = LowerBound rel valueExpr : lowerBounds, ..}, unused)
        else
          if coeff > 0
            then (Bounds {upperBounds = UpperBound rel valueExpr : upperBounds, ..}, unused)
            else (bounds, ineq : unused)

--------------------------------------------------------------------------------
-- Solutions

-- | Tries to reconstruct the value of the variable that is
-- consistent with the current assignment of variables. Returns either a
-- required variable that is missing from the assignment or the reconstructed
-- value.
reconstructFourierMotzkinVariableValue ::
  forall variable.
  (VariableLike variable) =>
  Bounds (LinearExpr variable RatTensor) ->
  Map variable RatTensor ->
  Either variable RatTensor
reconstructFourierMotzkinVariableValue solution assignment = do
  lowerBoundValues <- traverse (traverse (evaluateExpr assignment)) (lowerBounds solution)
  upperBoundValues <- traverse (traverse (evaluateExpr assignment)) (upperBounds solution)

  let maybeLowerBound = runSilentLogger $ andBoundList (mkDims []) lowerBoundValues
  let maybeUpperBound = runSilentLogger $ andBoundList (mkDims []) upperBoundValues

  return $ case (maybeLowerBound, maybeUpperBound) of
    (Nothing, Nothing) -> ZeroDimTensor 0
    (Just (LowerBound _ value), Nothing) -> mapTensor (+ 1) value
    (Nothing, Just (UpperBound _ value)) -> mapTensor (\x -> x - 1) value
    (Just (LowerBound rel1 value1), Just (UpperBound rel2 value2))
      -- UNSOUND over FP?
      | value1 < value2 || value1 == value2 && rel1 == NonStrict && rel2 == NonStrict ->
          zipWithTensor (\u v -> 0.5 * (u + v)) value1 value2
      | otherwise -> do
          -- Only 99% sure about this. Can't find a good reference to the reconstruction phase of the
          -- algorithm. Closest to referencing this impossibility is:
          -- https://people.math.carleton.ca/~kcheung/math/notes/MATH5801/02/2_1_fourier_motzkin.html
          developerError "Fourier-Motzkin reconstruction failed. This isn't supposed to be possible..."
