-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

{-# OPTIONS --allow-exec #-}

open import Vehicle
open import Vehicle.Data.Tensor
open import Data.Nat as ℕ using (ℕ)
open import Data.Fin as Fin using (Fin; #_)
open import Data.List

module simple-tensor-temp-output where

zeroD : Tensor ℕ []
zeroD = 2

oneD : Tensor ℕ (2 ∷ [])
oneD = zeroD ∷ (1 ∷ [])

twoD : Tensor ℕ (2 ∷ (2 ∷ []))
twoD = oneD ∷ ((2 ∷ (3 ∷ [])) ∷ [])

lookup2D : ℕ
lookup2D = twoD (# 0) (# 1)