-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata
--  - Agda version: 2.6.2
--  - AISEC version: 0.1.0.1
--  - Time generated: ???

open import Data.Unit
open import Data.List
open import Data.List.Relation.Unary.All as List

module MyTestModule where

emptyList : List ℤ
emptyList = []

empty : List.All (λ (x : ℤ) → ⊤) emptyList
empty = checkProperty record
  { databasePath = DATABASE_PATH
  ; propertyUUID = ????
  }