#!/bin/sh

# POSIX compliant method for 'pipefail':
fail=$(mktemp)

# Check if 'ghcup' is on the PATH:
ghcup=$(which ghcup || echo > "$fail")

# Check if 'cabal' is on the PATH:
cabal=$(which cabal || echo > "$fail")

# Get the project file from the environment:
PROJECT_FILE_BASE="${PROJECT_FILE-cabal.project}"

# Get the GHC version from the arguments:
GHC_VERSION="$1"
if expr "${GHC_VERSION}" : "[0-9]*\.[0-9]*\.[0-9]*" > /dev/null; then
    # Switch to correct GHC version
    OLD_GHC_VERSION=$(ghc --numeric-version)
    if [ "${GHC_VERSION}" != "${OLD_GHC_VERSION}" ]; then
        echo "Switching to GHC ${GHC_VERSION}"
        $ghcup set ghc "${GHC_VERSION}"
    fi

    # Create cabal.project.ghc-X.Y.Z
    PROJECT_FILE="${PROJECT_FILE_BASE}.ghc-${GHC_VERSION}"
    echo "Linking ${PROJECT_FILE_BASE} to ${PROJECT_FILE}"
    [ ! -f "${PROJECT_FILE}" ] && ln -s "${PROJECT_FILE_BASE}" "${PROJECT_FILE}"

    # Update Cabal package list
    $cabal update

    # Create cabal.project.ghc-X.Y.Z.freeze
    echo "Generating ${PROJECT_FILE}.freeze"
    [ ! -f "${PROJECT_FILE}.freeze" ] && $cabal v2-freeze --project-file="${PROJECT_FILE}"

    # Switch back to previous GHC version
    if [ "${GHC_VERSION}" != "${OLD_GHC_VERSION}" ]; then
        echo "Switching to GHC ${OLD_GHC_VERSION}"
        $ghcup set ghc "${OLD_GHC_VERSION}"
    fi

    # Check whether or not any subcommand failed:
    if [ -s "$fail" ]; then
        rm "$fail"
        exit 1
    else
        rm "$fail"
        exit 0
    fi
else
    rm "$fail"
    echo "Usage: cabal-freeze [X.Y.Z]"
    exit 1
fi
