#!/bin/sh

# POSIX compliant method for 'pipefail':
fail=$(mktemp)

# Check the HEAP_PROFILE_TYPE setting:
HEAP_PROFILE_TYPE="${HEAP_PROFILE_TYPE--hT}"
if [ "$HEAP_PROFILE_TYPE" = "-hT" ]; then
  echo "Type of profile: Basic heap profile"
elif [ "$HEAP_PROFILE_TYPE" = "-hi" ]; then
  echo "Type of profile: Info table profile"
else
  echo "Usage: HEAP_PROFILE_TYPE=[-hT or -hi] ./scripts/vehicle-profile [VEHICLE OPTIONS]"
  echo "Error: expected HEAP_PROFILE_TYPE to be -hT or -hi, found $HEAP_PROFILE_TYPE"
fi

# Create the directory for profiling files:
PROFILING_DIR=".profiling"
[ ! -s "$fail" ] && (mkdir -p "$PROFILING_DIR" || echo > "$fail")

# Create the timestamped filenames for profiling files:
TIMESTAMP=$(awk 'BEGIN{srand(); print srand()}')
PROFILING_PREFIX="$PROFILING_DIR/vehicle-$TIMESTAMP"
EVENTLOG_FILE="$PROFILING_PREFIX$HEAP_PROFILE_TYPE.eventlog"

# Run vehicle in debug mode with the given options.
# Produce a heap profile grouped by closure type (-hT).
RTSOPTS="+RTS -po"$PROFILING_PREFIX" -ol"$EVENTLOG_FILE" -s -l "${HEAP_PROFILE_TYPE}" -RTS"
VEHICLE="cabal -v0 --project-file=cabal.project.debug run exe:vehicle --"
[ ! -s "$fail" ] && ($VEHICLE $@ $RTSOPTS || echo > "$fail")

# Convert the heap profile to an HTML page.
EVENTLOG2HTML="eventlog2html"
[ ! -s "$fail" ] && ($EVENTLOG2HTML "$EVENTLOG_FILE" || echo > "$fail")

# Output the path to the generated HTML page.
EVENTLOG_HTML="$EVENTLOG_FILE.html"
[ ! -s "$fail" ] && (echo "Wrote eventlog to $EVENTLOG_FILE.html")

# Check whether or not any subcommand failed:
if [ -s "$fail" ]; then
  rm "$fail"
  exit 1
else
  rm "$fail"
fi

# Open the eventlog in a browser
# See: https://en.wikipedia.org/wiki/Uname#Examples
OPERATING_SYSTEM=$(uname -s)
if [ "$OPERATING_SYSTEM" = "Darwin" ]
then
  open "$EVENTLOG_HTML"
elif [ "$OPERATING_SYSTEM" = "Linux" ]
then
  # Use BROWSER environment variable?
  # [ "$BROWSER" = "" ] || $BROWSER "$EVENTLOG_HTML"
  :
else
  OPERATING_SYSTEM="$(echo "$OPERATING_SYSTEM" | cut -d - -f 1)"
  if [ "$OPERATING_SYSTEM" = "CYGWIN_NT" \
    -o "$OPERATING_SYSTEM" = "MINGW64_NT" \
    -o "$OPERATING_SYSTEM" = "MSYS_NT" ]; then
    # Use default browser on Windows? Open via PowerShell?
    # start "" "$EVENTLOG_HTML"
    :
  else
    # Unsupported operating system?
    :
  fi
fi
