module Vehicle.Backend.Prelude where

import Control.Monad.IO.Class (MonadIO (..))
import Data.Text qualified as Text
import Data.Text.IO qualified as TIO
import System.Directory (createDirectoryIfMissing)
import System.FilePath (takeDirectory)
import Vehicle.Prelude
import Vehicle.Prelude.IO qualified as VIO (MonadStdIO (writeStdoutLn))
import Vehicle.Prelude.Logging

--------------------------------------------------------------------------------
-- Builtin Differentiable Logics

data BuiltinDifferentiableLogicID
  = VehicleLoss
  | DL2Loss
  deriving (Eq, Show, Read, Enum, Bounded)

instance Pretty BuiltinDifferentiableLogicID where
  pretty = pretty . show

--------------------------------------------------------------------------------
-- Differentiable logics

-- | Different ways of translating from the logical constraints to loss functions.
data DifferentiableLogicID
  = BuiltinLogic BuiltinDifferentiableLogicID
  | CustomLogic Name
  deriving (Eq, Show)

instance Read DifferentiableLogicID where
  readsPrec _prec value = do
    let maybeLogicID = lookupEnumerable @BuiltinDifferentiableLogicID show value
    let logicID = maybe (CustomLogic $ Text.pack value) BuiltinLogic maybeLogicID
    [(logicID, "")]

instance Pretty DifferentiableLogicID where
  pretty = \case
    BuiltinLogic logic -> pretty logic
    CustomLogic name -> pretty name

instance HasName DifferentiableLogicID Name where
  nameOf logicID = layoutAsText $ pretty logicID

--------------------------------------------------------------------------------
-- Interactive theorem provers

data InteractiveTheoremProverID
  = Agda
  | Rocq
  | Isabelle
  | Imandra
  deriving (Eq, Show, Read, Bounded, Enum)

instance Pretty InteractiveTheoremProverID where
  pretty = pretty . show

--------------------------------------------------------------------------------
-- Different type-checking modes

data SecondaryTypeSystem
  = PolarityTypes
  | LinearityTypes
  | DecidabilityTypes
  | GradientCarryingTypes
  deriving (Eq, Show, Bounded, Enum)

instance Pretty SecondaryTypeSystem where
  pretty = \case
    PolarityTypes -> "Polarity"
    LinearityTypes -> "Linearity"
    DecidabilityTypes -> "Decidability"
    GradientCarryingTypes -> "GradientCarryingTypes"

instance Read SecondaryTypeSystem where
  readsPrec _d x = case x of
    "Linearity" -> [(LinearityTypes, [])]
    "Polarity" -> [(PolarityTypes, [])]
    "Decidability" -> [(DecidabilityTypes, [])]
    "GradientCarryingTypes" -> [(GradientCarryingTypes, [])]
    _ -> []

--------------------------------------------------------------------------------
-- Action

-- | Generate the file header given the token used to start comments in the
--  target language
prependfileHeader :: forall a. Doc a -> Maybe ExternalOutputFormat -> Doc a
prependfileHeader doc format = case format of
  Nothing -> doc
  Just ExternalOutputFormat {..} -> do
    let vehicleVersionLine = " - Vehicle version:" <+> pretty impreciseVehicleVersion
    let formatVersionLines = maybe [] (\v -> [" -" <+> formatName <> " version:" <+> pretty v]) formatVersion

    let headerLines =
          [ "WARNING: This file was generated automatically by Vehicle",
            "and should not be modified manually!",
            "Metadata:",
            vehicleVersionLine
          ]
            <> formatVersionLines

    let commentLine l = case commentStyle of
          Line t -> t <+> l
          Block s e -> s <+> l <+> e
    let header = vsep (map commentLine headerLines)

    header
      <> line
      -- Marabou query format doesn't current support empty lines.
      -- See https://github.com/NeuralNetworkVerification/Marabou/issues/625
      <> (if emptyLines then line else "")
      <> doc

writeResultToFile ::
  (MonadStdIO m, MonadLogger m) =>
  Maybe ExternalOutputFormat ->
  Maybe FilePath ->
  Doc a ->
  m ()
writeResultToFile = writeResultToFileWith layoutAsText

writeResultToFileWide ::
  (MonadStdIO m, MonadLogger m) =>
  Maybe ExternalOutputFormat ->
  Maybe FilePath ->
  Doc a ->
  m ()
writeResultToFileWide = writeResultToFileWith layoutAsTextWide

writeResultToFileWith ::
  (MonadStdIO m, MonadLogger m) =>
  (Doc a -> Text.Text) ->
  Maybe ExternalOutputFormat ->
  Maybe FilePath ->
  Doc a ->
  m ()
writeResultToFileWith layout target filepath doc = do
  let text = layout $ prependfileHeader doc target
  case filepath of
    Nothing -> VIO.writeStdoutLn text
    Just outputFilePath -> do
      logDebug MinDetail $ "Creating file:" <+> pretty filepath
      liftIO $ do
        createDirectoryIfMissing True (takeDirectory outputFilePath)
        TIO.writeFile outputFilePath text
