"""Auto-generated by vehicle-lang from spec.vcl. Do not edit."""

from __future__ import annotations

import torch
from jaxtyping import Float
from torch import Tensor

__vehicle_schema_digest__ = "b991f606c5eb01f3"


class Pair(torch.Tensor):  # type: ignore[misc]
    # Make torch.* ops return plain Tensor, not this subclass.
    __torch_function__ = torch._C._disabled_torch_function_impl

    _FIELDS: tuple[str, ...] = ("a", "b")
    _FLAT_WIDTH: int = 2
    _FIELD_SLOTS: dict[str, tuple[int, int]] = {
        "a": (0, 1),
        "b": (1, 2),
    }

    @staticmethod
    def __new__(cls, *, _from_tensor: Tensor | None = None, **fields: Tensor) -> "Pair":
        if _from_tensor is not None:
            return _from_tensor.as_subclass(cls)  # type: ignore[no-any-return]
        slabs = []
        v_a = torch.as_tensor(fields["a"])
        slabs.append(v_a.reshape(*v_a.shape, 1))
        v_b = torch.as_tensor(fields["b"])
        slabs.append(v_b.reshape(*v_b.shape, 1))
        return torch.cat(slabs, dim=-1).as_subclass(cls)  # type: ignore[no-any-return]

    @classmethod
    def from_tensor(cls, t: Tensor) -> "Pair":
        return t.as_subclass(cls)  # type: ignore[no-any-return]

    def to_tensor(self) -> Tensor:
        return self.as_subclass(torch.Tensor)

    @property
    def a(self) -> Float[Tensor, ""]:
        lo, hi = Pair._FIELD_SLOTS["a"]
        base = self.as_subclass(torch.Tensor)[..., lo:hi]
        return base.reshape(self.shape[:-1])

    @property
    def b(self) -> Float[Tensor, ""]:
        lo, hi = Pair._FIELD_SLOTS["b"]
        base = self.as_subclass(torch.Tensor)[..., lo:hi]
        return base.reshape(self.shape[:-1])
