"""Auto-generated by vehicle-lang from spec.vcl. Do not edit."""

from __future__ import annotations

from dataclasses import dataclass

from jaxtyping import Float
from torch import Tensor


@dataclass(frozen=True)
class Pair:
    a: Float[Tensor, ""]
    b: Float[Tensor, ""]
