module Vehicle.Data.Bound.FourierMotzkinElimination
  ( fourierMotzkinSliceBoundsElimination,
    fourierMotzkinTensorBoundsEliminationWithErrors,
    fourierMotzkinTensorBoundsElimination,
  )
where

-- \| TODO If performance proves unnacceptably poor look into
-- Imbert's acceleration theorems:
--
-- Jean-Louis Imbert,
-- About Redundant Inequalities Generated by Fourier's Algorithm
-- Artificial Intelligence IV: Methodology, Systems, Applications, 1990

import Control.Monad (zipWithM)
import Control.Monad.Identity (Identity (..))
import Control.Monad.Reader (MonadReader (..), ReaderT (..), asks)
import Data.Either (partitionEithers)
import Data.List.NonEmpty (NonEmpty (..))
import Vehicle.Compile.Constants.ForcedValue ()
import Vehicle.Compile.Constants.Rational (LinearExpression)
import Vehicle.Compile.Error
import Vehicle.Compile.Normalise.Builtin (evalConstTensor, forceEvaluation)
import Vehicle.Compile.Prelude
import Vehicle.Data.Assertion
import Vehicle.Data.Bound
import Vehicle.Data.Builtin.Standard
import Vehicle.Data.Code.BooleanExpr (ConjunctAll (..), eliminateTrivialConjunctions)
import Vehicle.Data.Code.ForcedValue (DimensionedTensorValue (..), GenericThunk (..), Thunk)
import Vehicle.Data.Code.Interface (ConstTensorArgs (..))
import Vehicle.Data.Code.Interface.Operations (accessConstTensor)
import Vehicle.Data.Code.Interface.Patterns
import Vehicle.Data.Code.LinearExpr
import Vehicle.Data.MaybeTrivial (MaybeTrivial (..))
import Vehicle.Data.Real (ExtendedRational (..))
import Vehicle.Data.Tensor
import Vehicle.Data.Variable.Bound.Context.Name
import Vehicle.Data.Variable.Bound.Context.Tensor.Core (KnownPrefixOfTensorShape)
import Vehicle.Data.Variable.Free.Context (MonadFreeContext)

--------------------------------------------------------------------------------
-- Tensor traversal

type MonadTraverseTensor m = MonadReader TensorIndices m

traverseTensorRows :: (MonadTraverseTensor m) => (a -> m b) -> [a] -> m [b]
traverseTensorRows f rows = do
  let fLocal (i, v) = local (i :) (f v)
  traverse fLocal (zip [0 ..] rows)

currentIndices :: (MonadTraverseTensor m) => m TensorIndices
currentIndices = asks reverse

runTraverseTensorT ::
  (Monad m) =>
  ReaderT TensorIndices m a ->
  m a
runTraverseTensorT action = runReaderT action mempty

--------------------------------------------------------------------------------
-- Tensor traversal

-- | Takes in bounds over a tensor and tries to compute a single lower and upper bound for the
-- whole tensor. If it fails then it returns a list of the indices of the tensor which
-- are unbounded.
--
-- NOTE: this function is currently unsound as at the moment it discards the strictness information.
-- See https://github.com/vehicle-lang/vehicle/issues/74
fourierMotzkinTensorBoundsEliminationWithErrors ::
  (MonadLogger m, MonadReadableNameContext m, ConstantLike constant (ReaderT TensorIndices m)) =>
  TensorBounds constant ->
  m (Either UnboundedIndices (Domain constant))
fourierMotzkinTensorBoundsEliminationWithErrors TensorBounds {..} = do
  errorOrLowerBound <- runTraverseTensorT (go lowerBounds tensorSliceBounds)
  errorOrUpperBounds <- runTraverseTensorT (go upperBounds tensorSliceBounds)
  return $ theseErrors Domain errorOrLowerBound errorOrUpperBounds
  where
    go ::
      (MonadLogger m, MonadReadableNameContext m, MonadTraverseTensor m, IsBound bound expr m) =>
      (SliceBounds expr -> [bound expr]) ->
      NestedSliceBounds expr ->
      m (Either (NonEmpty TensorIndices) (bound expr))
    go getBound (NestedSliceBounds sliceBounds maybeChildBounds) = do
      maybeBounds <- andBoundList (getBound sliceBounds)
      case (maybeChildBounds, maybeBounds) of
        (Nothing, Nothing) -> do
          indices <- currentIndices
          return $ Left [indices]
        (Nothing, Just bounds) ->
          return $ Right bounds
        (Just childTensorBounds, _) -> do
          childErrorOrBounds <- traverseTensorRows (go getBound) childTensorBounds
          let (missingChildIndices, childBounds) = partitionEithers childErrorOrBounds
          case maybeBounds of
            Nothing -> case missingChildIndices of
              i : is -> return $ Left $ concatNonEmpty $ i :| is
              [] -> Right <$> stackBounds childBounds
            Just bound -> do
              case missingChildIndices of
                _ : _ -> do
                  boundElements <- unstackBounds bound
                  let combineBound boundElement = either (const (return boundElement)) (andBound boundElement)
                  combinedElements <- zipWithM combineBound boundElements childErrorOrBounds
                  Right <$> stackBounds combinedElements
                [] -> do
                  childBound <- stackBounds childBounds
                  Right <$> andBound bound childBound

-- | Takes in bounds over a tensor and computes a single lower and upper bound for the
-- whole tensor, filling in any missing bounds with the default.
--
-- NOTE: this function is currently unsound as at the moment it discards the strictness information.
-- See https://github.com/vehicle-lang/vehicle/issues/74
fourierMotzkinTensorBoundsElimination ::
  forall m.
  (MonadLogger m, MonadFreeContext Builtin m, MonadNameContext m, MonadReadableNameContext m) =>
  (KnownPrefixOfTensorShape, Thunk Builtin) ->
  TensorBounds (DimensionedTensorValue Builtin) ->
  m (Domain (DimensionedTensorValue Builtin))
fourierMotzkinTensorBoundsElimination (fullKnownPrefix, remainingShape) TensorBounds {..} = do
  lowerBound <- go NegInfinity fullKnownPrefix lowerBounds tensorSliceBounds
  upperBound <- go PosInfinity fullKnownPrefix upperBounds tensorSliceBounds
  return $ Domain lowerBound upperBound
  where
    go ::
      (IsBound bound (DimensionedTensorValue Builtin) m) =>
      ExtendedRational ->
      KnownPrefixOfTensorShape ->
      (SliceBounds (DimensionedTensorValue Builtin) -> [bound (DimensionedTensorValue Builtin)]) ->
      NestedSliceBounds (DimensionedTensorValue Builtin) ->
      m (bound (DimensionedTensorValue Builtin))
    go defaultBound knownPrefix getBound (NestedSliceBounds sliceBounds maybeChildBounds) = do
      maybeBounds <- andBoundList (getBound sliceBounds)
      case (knownPrefix, maybeChildBounds, maybeBounds) of
        (_, Nothing, Nothing) -> do
          let dims = foldr (\d ds -> Forced $ IDimCons (Forced (INatLiteral d)) ds) remainingShape knownPrefix
          let args = ConstTensorArgs (Forced IRatType) (Forced $ IRatLiteral defaultBound) dims
          value <- forceEvaluation accessConstTensor evalConstTensor args
          valueToBound (Strict, TensorValue dims value)
        (_, Nothing, Just bounds) ->
          return bounds
        (_d : ds, Just childTensorBounds, _) -> do
          childBounds <- traverse (go defaultBound ds getBound) childTensorBounds
          case maybeBounds of
            Nothing -> stackBounds childBounds
            Just bound -> do
              childBound <- stackBounds childBounds
              andBound bound childBound
        _ -> developerError $ "malformed tensor prefix" <+> pretty fullKnownPrefix

fourierMotzkinSliceBoundsElimination ::
  (MonadCompile m, MonadReadableNameContext m) =>
  SliceBounds LinearExpression ->
  m (MaybeTrivial (ConjunctAll (Inequality LinearExpression)))
fourierMotzkinSliceBoundsElimination (SliceBounds lower upper) = do
  let newMaybeTrivialInequalities = cartesianProduct combineInequalities lower upper
  let maybeTrivialFinalInequalities = case newMaybeTrivialInequalities of
        [] -> Trivial True
        x : xs -> eliminateTrivialConjunctions (ConjunctAll (x :| xs))

  return maybeTrivialFinalInequalities

combineInequalities ::
  LowerBound LinearExpression ->
  UpperBound LinearExpression ->
  MaybeTrivial (Inequality LinearExpression)
combineInequalities (LowerBound rel1 lowerBound) (UpperBound rel2 upperBound) = do
  let maybeNewExpr = runIdentity $ addExprs 1 (-1) lowerBound upperBound
  let newRel = combineInequalityRelations rel1 rel2
  case maybeNewExpr of
    Left tensor -> Trivial $ isRelated newRel tensor (ConstantTensor (shapeOf tensor) 0)
    Right newExpr -> NonTrivial $ NormalisedRelation newRel newExpr
