module Vehicle.Data.Bound.FourierMotzkinElimination
  ( fourierMotzkinSliceBoundsElimination,
    fourierMotzkinTensorBoundsElimination,
  )
where

-- \| TODO If performance proves unnacceptably poor look into
-- Imbert's acceleration theorems:
--
-- Jean-Louis Imbert,
-- About Redundant Inequalities Generated by Fourier's Algorithm
-- Artificial Intelligence IV: Methodology, Systems, Applications, 1990

import Data.Either (partitionEithers)
import Data.List.NonEmpty (NonEmpty (..))
import Vehicle.Compile.Error
import Vehicle.Compile.Prelude
import Vehicle.Compile.Print
import Vehicle.Data.Assertion
import Vehicle.Data.Bound
import Vehicle.Data.Code.BooleanExpr (ConjunctAll (..), eliminateTrivialConjunctions)
import Vehicle.Data.Code.LinearExpr
import Vehicle.Data.MaybeTrivial (MaybeTrivial (..))
import Vehicle.Data.Tensor
import Vehicle.Data.Tensor.Traversal
import Vehicle.Data.Variable.Bound.Context.Name
import Vehicle.Data.Variable.Bound.Level

-- | Takes in bounds over a tensor and tries to compute a single lower and upper bound for the
-- whole tensor. If it fails then it returns a list of the indices of the tensor which
-- are unbounded.
--
-- NOTE: this function is currently unsound as at the moment it discards the strictness information.
-- See https://github.com/vehicle-lang/vehicle/issues/74
fourierMotzkinTensorBoundsElimination ::
  (MonadLogger m, MonadReadableNameContext m, ConstantLike constant) =>
  PartiallyKnownTensorShape ->
  TensorBounds constant ->
  m (Either UnboundedIndices (Domain constant))
fourierMotzkinTensorBoundsElimination partialShape TensorBounds {..} = do
  errorOrLowerBound <- runTraverseTensorT partialShape (flattenNestedSliceBounds lowerBounds tensorSliceBounds)
  errorOrUpperBounds <- runTraverseTensorT partialShape (flattenNestedSliceBounds upperBounds tensorSliceBounds)
  return $ theseErrors Domain errorOrLowerBound errorOrUpperBounds

flattenNestedSliceBounds ::
  forall m bound expr.
  (MonadLogger m, MonadReadableNameContext m, MonadTraverseTensor m, IsBound bound expr) =>
  (SliceBounds expr -> [bound expr]) ->
  NestedSliceBounds expr ->
  m (Either (NonEmpty TensorIndices) (bound expr))
flattenNestedSliceBounds getBound = go
  where
    go ::
      NestedSliceBounds expr ->
      m (Either (NonEmpty TensorIndices) (bound expr))
    go (NestedSliceBounds sliceBounds maybeChildBounds) = case maybeChildBounds of
      Nothing -> case andBoundList (getBound sliceBounds) of
        Just bounds -> return $ Right bounds
        Nothing -> do
          indices <- currentIndices
          return $ Left [indices]
      Just childTensorBounds -> do
        childErrorOrBounds <- traverseTensorRows go childTensorBounds
        let (missingChildIndices, childBounds) = partitionEithers childErrorOrBounds
        case andBoundList (getBound sliceBounds) of
          Nothing -> case missingChildIndices of
            i : is -> return $ Left $ concatNonEmpty $ i :| is
            [] -> return $ Right $ stackBounds childBounds
          Just bound -> do
            case missingChildIndices of
              _ : _ -> do
                let boundElements = unstackBounds bound
                let combineBound boundElement = either (const boundElement) (andBound boundElement)
                let combinedElements = zipWith combineBound boundElements childErrorOrBounds
                return $ Right $ stackBounds combinedElements
              [] -> do
                let childBound = stackBounds childBounds
                return $ Right $ andBound bound childBound

fourierMotzkinSliceBoundsElimination ::
  (MonadCompile m, MonadReadableNameContext m, ConstantLike constant, PrettyFriendly (constant `In` NamedBoundCtx)) =>
  SliceBounds (LinearExpr SliceVariable constant) ->
  m (MaybeTrivial (ConjunctAll (Inequality (LinearExpr SliceVariable constant))))
fourierMotzkinSliceBoundsElimination (SliceBounds lower upper) = do
  let newMaybeTrivialInequalities = cartesianProduct combineInequalities lower upper
  let maybeTrivialFinalInequalities = case newMaybeTrivialInequalities of
        [] -> Trivial True
        x : xs -> eliminateTrivialConjunctions (ConjunctAll (x :| xs))

  return maybeTrivialFinalInequalities

combineInequalities ::
  (VariableLike variable, ConstantLike constant) =>
  LowerBound (LinearExpr variable constant) ->
  UpperBound (LinearExpr variable constant) ->
  MaybeTrivial (Inequality (LinearExpr variable constant))
combineInequalities (LowerBound rel1 lowerBound) (UpperBound rel2 upperBound) = do
  let maybeNewExpr = addExprs 1 (-1) lowerBound upperBound
  let newRel = combineInequalityRelations rel1 rel2
  case maybeNewExpr of
    Left constant -> Trivial $ evalTrivialRelation newRel constant
    Right newExpr -> NonTrivial $ NormalisedRelation newRel newExpr
