module Vehicle.Data.Bound.FourierMotzkinElimination
  ( fourierMotzkinSliceBoundsElimination,
    fourierMotzkinTensorBoundsElimination,
  )
where

-- \| TODO If performance proves unnacceptably poor look into
-- Imbert's acceleration theorems:
--
-- Jean-Louis Imbert,
-- About Redundant Inequalities Generated by Fourier's Algorithm
-- Artificial Intelligence IV: Methodology, Systems, Applications, 1990

import Control.Monad (zipWithM)
import Control.Monad.Identity (Identity (..))
import Control.Monad.Reader (ReaderT)
import Data.Either (partitionEithers)
import Data.List.NonEmpty (NonEmpty (..))
import Vehicle.Compile.Constants.Rational (LinearExpression)
import Vehicle.Compile.Error
import Vehicle.Compile.Prelude
import Vehicle.Data.Assertion
import Vehicle.Data.Bound
import Vehicle.Data.Code.BooleanExpr (ConjunctAll (..), eliminateTrivialConjunctions)
import Vehicle.Data.Code.LinearExpr
import Vehicle.Data.MaybeTrivial (MaybeTrivial (..))
import Vehicle.Data.Tensor
import Vehicle.Data.Tensor.Traversal
import Vehicle.Data.Variable.Bound.Context.Name

-- | Takes in bounds over a tensor and tries to compute a single lower and upper bound for the
-- whole tensor. If it fails then it returns a list of the indices of the tensor which
-- are unbounded.
--
-- NOTE: this function is currently unsound as at the moment it discards the strictness information.
-- See https://github.com/vehicle-lang/vehicle/issues/74
fourierMotzkinTensorBoundsElimination ::
  (MonadLogger m, MonadReadableNameContext m, ConstantLike constant (ReaderT TensorIndices m)) =>
  TensorBounds constant ->
  m (Either UnboundedIndices (Domain constant))
fourierMotzkinTensorBoundsElimination TensorBounds {..} = do
  errorOrLowerBound <- runTraverseTensorT (flattenNestedSliceBounds lowerBounds tensorSliceBounds)
  errorOrUpperBounds <- runTraverseTensorT (flattenNestedSliceBounds upperBounds tensorSliceBounds)
  return $ theseErrors Domain errorOrLowerBound errorOrUpperBounds

flattenNestedSliceBounds ::
  forall m bound expr.
  (MonadLogger m, MonadReadableNameContext m, MonadTraverseTensor m, IsBound bound expr m) =>
  (SliceBounds expr -> [bound expr]) ->
  NestedSliceBounds expr ->
  m (Either (NonEmpty TensorIndices) (bound expr))
flattenNestedSliceBounds getBound = go
  where
    go ::
      NestedSliceBounds expr ->
      m (Either (NonEmpty TensorIndices) (bound expr))
    go (NestedSliceBounds sliceBounds maybeChildBounds) = do
      maybeBounds <- andBoundList (getBound sliceBounds)
      case (maybeChildBounds, maybeBounds) of
        (Nothing, Nothing) -> do
          indices <- currentIndices
          return $ Left [indices]
        (Nothing, Just bounds) ->
          return $ Right bounds
        (Just childTensorBounds, _) -> do
          childErrorOrBounds <- traverseTensorRows go childTensorBounds
          let (missingChildIndices, childBounds) = partitionEithers childErrorOrBounds
          case maybeBounds of
            Nothing -> case missingChildIndices of
              i : is -> return $ Left $ concatNonEmpty $ i :| is
              [] -> Right <$> stackBounds childBounds
            Just bound -> do
              case missingChildIndices of
                _ : _ -> do
                  boundElements <- unstackBounds bound
                  let combineBound boundElement = either (const (return boundElement)) (andBound boundElement)
                  combinedElements <- zipWithM combineBound boundElements childErrorOrBounds
                  Right <$> stackBounds combinedElements
                [] -> do
                  childBound <- stackBounds childBounds
                  Right <$> andBound bound childBound

fourierMotzkinSliceBoundsElimination ::
  (MonadCompile m, MonadReadableNameContext m) =>
  SliceBounds LinearExpression ->
  m (MaybeTrivial (ConjunctAll (Inequality LinearExpression)))
fourierMotzkinSliceBoundsElimination (SliceBounds lower upper) = do
  let newMaybeTrivialInequalities = cartesianProduct combineInequalities lower upper
  let maybeTrivialFinalInequalities = case newMaybeTrivialInequalities of
        [] -> Trivial True
        x : xs -> eliminateTrivialConjunctions (ConjunctAll (x :| xs))

  return maybeTrivialFinalInequalities

combineInequalities ::
  LowerBound LinearExpression ->
  UpperBound LinearExpression ->
  MaybeTrivial (Inequality LinearExpression)
combineInequalities (LowerBound rel1 lowerBound) (UpperBound rel2 upperBound) = do
  let maybeNewExpr = runIdentity $ addExprs 1 (-1) lowerBound upperBound
  let newRel = combineInequalityRelations rel1 rel2
  case maybeNewExpr of
    Left tensor -> Trivial $ isRelated newRel tensor (ConstantTensor (shapeOf tensor) 0)
    Right newExpr -> NonTrivial $ NormalisedRelation newRel newExpr
