name: "Setup Haskell"
description: "Setup Haskell"
inputs:
  python-version:
    required: false
    description: "Version of Python to use."
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-cache-${{ runner.os }}-${{ runner.arch }}-python-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
