cabal-version:   3.4
name:            vehicle-lsp
version:         0.0.0.0
synopsis:        Language Server for the Vehicle language
description:     Language Server for the Vehicle language.
author:          Wen Kokke
maintainer:      wenkokke@users.noreply.github.com
build-type:      Simple
category:        Language
extra-doc-files: CHANGELOG.md

common language
  ghc-options:
    -Wall -Wcompat -Widentities -Wprepositive-qualified-module
    -Wredundant-constraints -Wunticked-promoted-constructors
    -Wunused-packages

  default-language:   GHC2021
  default-extensions: ImportQualifiedPost

library
  import:          language
  hs-source-dirs:  src
  build-depends:
    , aeson                 >=2.2     && <2.3
    , base                  >=4.13    && <5
    , co-log                >=0.6     && <0.7
    , co-log-core           >=0.3     && <0.4
    , data-default          >=0.7     && <0.8
    , lsp                   >=2.7.0.1 && <2.8
    , lsp-types             >=2.3     && <2.4
    , optparse-applicative  >=0.18    && <0.19
    , prettyprinter         >=1.7     && <1.8
    , stm                   >=2.5     && <2.6
    , text                  >=2.1     && <2.2
    , unliftio-core         >=0.2     && <0.3

  exposed-modules: Vehicle.LSP
  other-modules:
    Vehicle.LSP.Internal.Config
    Vehicle.LSP.Internal.Handlers
    Paths_vehicle_lsp

  autogen-modules: Paths_vehicle_lsp

executable vehicle-lsp
  import:         language
  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:
    , base
    , vehicle-lsp
