module Vehicle.Backend.Marabou.Core where

import Vehicle.Prelude
import Vehicle.Compile.Resource (MetaNetwork)
import Vehicle.Compile.Linearity.Core (UserVarReconstructionInfo)

type MarabouSpec = [(Symbol, MarabouProperty)]

data MarabouProperty
  = SingleProperty Bool [MarabouQuery]
  -- | A single property.
  -- The bool denotes if the property is negated.
  -- The queries are implicitly disjuncted.
  | MultiProperty  [MarabouProperty]
  -- | Multiple sub-properties e.g. generated by a `foreach`.
  -- They are implicitly conjuncted.

data MarabouQuery = MarabouQuery
  { doc               :: Doc ()
  , vars              :: [Symbol]
  , metaNetwork       :: MetaNetwork
  , varReconstruction :: UserVarReconstructionInfo
  }