module Vehicle.Backend.Marabou.Core where

import Vehicle.Prelude
import Vehicle.Resource.NeuralNetwork (MetaNetwork)

type MarabouSpec = [(Symbol, MarabouProperty)]

data MarabouProperty
  = SingleProperty Bool [MarabouQuery]
  -- | A single property.
  -- The bool denotes if the property is negated.
  -- The queries are implicitly disjuncted.
  | MultiProperty  [MarabouProperty]
  -- | Multiple sub-properties e.g. generated by a `foreach`.
  -- They are implicitly conjuncted.

data MarabouQuery = MarabouQuery
  { doc         :: Doc ()
  , vars        :: [MarabouVar]
  , metaNetwork :: MetaNetwork
  }

data MarabouVar = MarabouVar
  { name    :: Symbol         -- Name of the variable
  , varType :: MarabouVarType -- Type of the variable
  }

data MarabouVarType
  = MReal
