name: Build py-vehicle-tensorflow

on:
  workflow_call:
  workflow_dispatch:

env:
  DEFAULT_GHC_VERSION: "9.4.4"
  DEFAULT_CABAL_VERSION: "3.10.1.0"

jobs:
  build-py-vehicle-tensorflow:
    name: py-vehicle-tensorflow / ${{ matrix.os.name }} - Python ${{ matrix.python.version }}
    runs-on: ${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - { version: ubuntu-latest, name: Linux }
          - { version: macos-latest, name: macOS }
          # ??-??-????:
          # This test is disabled on Windows due to some unspecified issue.
          # - { version: windows-latest, name: Windows }
        python:
          - { version: "3.8", tag: "38" }
          - { version: "3.9", tag: "39" }
          - { version: "3.10", tag: "311" }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Vehicle
        uses: ./.github/actions/setup-vehicle
        with:
          vehicle-artifact-name: |
            vehicle-${{ runner.arch }}-${{ runner.os }}-ghc-${{ env.DEFAULT_GHC_VERSION }}-${{ github.sha }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          cache: "pip"
          cache-dependency-path: "py-vehicle-tensorflow/pyproject.toml"

      - name: Test
        run: |
          python -m pip install .[test]
          python -m unittest tests/test_LossFunctionTranslation.py
        shell: sh
        working-directory: py-vehicle-tensorflow
