name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc-version: ["8.10", "9.0"]
        cabal-version: ["3.4"]

    env:
      CABAL_PROJECT_FILE: cabal.project.ghc-${{ matrix.ghc-version }}
      CABAL_PROJECT_FREEZE_FILE: cabal.project.ghc-${{ matrix.ghc-version }}.freeze

    name: Build on ${{ matrix.os }} with GHC ${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}
          cabal-project-file: ${{ env.CABAL_PROJECT_FILE }}
          cabal-project-freeze-file: ${{ env.CABAL_PROJECT_FREEZE_FILE }}

      - name: Build Vehicle
        run: cabal v2-run vehicle-build-system build

      - name: Test Vehicle
        run: cabal v2-run vehicle-build-system basic-tests

      - name: Copy Vehicle binaries to dist/bin
        run: |
          mkdir -p ${{ github.workspace }}/dist/bin
          cabal install exe:vehicle \
            --overwrite-policy=always \
            --install-method=copy \
            --installdir=${{ github.workspace }}/dist/bin
        shell: bash

      - name: Upload Vehicle binaries
        uses: actions/upload-artifact@v2
        with:
          name: vehicle-${{ runner.arch }}-${{ runner.os }}
          path: ${{ github.workspace }}/dist/bin/*
