name: build

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-vehicle:
    name: ${{ matrix.os_and_name[1] }} / GHC ${{ matrix.ghc-version }}
    uses: ./.github/workflows/build-vehicle.yml
    with:
      runs-on: ${{ matrix.os_and_name[0] }}
      ghc-version: ${{ matrix.ghc-version }}
      cabal-version: ${{ matrix.cabal-version }}
    strategy:
      matrix:
        os_and_name:
          - [ubuntu-latest, Linux]
          - [macos-latest, macOS]
          - [windows-latest, Windows]
        ghc-version: ["8.10.7", "9.0.2", "9.2.4", "9.4.2"]
        cabal-version: ["3.8"]

  build-vehicle-python:
    name: ${{ matrix.os_and_name[1] }} / Python ${{ matrix.python-version }}
    needs: [build-vehicle]
    uses: ./.github/workflows/build-vehicle-python.yml
    with:
      runs-on: ${{ matrix.os_and_name[0] }}
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        os_and_name:
          - [ubuntu-latest, Linux]
          - [macos-latest, macOS]
          # - [windows-latest, Windows]
        python-version: ["3.9", "3.10"] # ["3.7", "3.8"]
        # include:
        #   - # Earliest supported version:
        #     os: ubuntu-latest
        #     python-version: "3.7.1"
