name: build

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-vehicle:
    name: ${{ matrix.os_and_name[1] }} / GHC ${{ matrix.ghc-version }}
    uses: ./.github/workflows/build-vehicle.yml
    with:
      runs-on: ${{ matrix.os_and_name[0] }}
      ghc-version: ${{ matrix.ghc-version }}
      cabal-version: ${{ matrix.cabal-version }}
    strategy:
      matrix:
        os_and_name:
          # NOTE: build-vehicle-python for Python 3.8.0 runs on Ubuntu 20.04,
          #       because Python 3.8.0 is not supported by setup-python.
          #       The vehicle executable built here will be dependent on libc,
          #       which is generally forwards but not backwards compatible.
          #       Therefore, we must build vehicle on Ubuntu 20.04.
          - [ubuntu-20.04, Linux]
          - [macos-latest, macOS]
          - [windows-latest, Windows]
        ghc-version: ["8.10.7", "9.0.2", "9.2.4", "9.4.2"]
        cabal-version: ["3.8"]

  build-vehicle-python:
    name: ${{ matrix.os_and_name[1] }} / Python ${{ matrix.python-version }}
    needs: [build-vehicle]
    uses: ./.github/workflows/build-vehicle-python.yml
    with:
      runs-on: ${{ matrix.os_and_name[0] }}
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        os_and_name:
          - [ubuntu-latest, Linux]
          - [macos-latest, macOS]
          # - [windows-latest, Windows]
        python-version: ["3.8", "3.9", "3.10"]
        include:
          - # Earliest supported version:
            os_and_name: [ubuntu-20.04, Linux]
            python-version: "3.8.0"

  # NOTE: This is a temporary workaround, because our tests fail with +nothunks.
  #       Once fixed, we should call build-vehicle with cabal.project.nothunks.
  build-vehicle-nothunks:
    name: Linux / GHC 9.2.4 / +nothunks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: "9.2.4"
          cabal-version: "3.8"
          cabal-project-file: cabal.project.nothunks.ghc-9.2.4
          cabal-project-freeze-file: cabal.project.nothunks.ghc-9.2.4.freeze

      - name: Build Vehicle
        run: cabal --project-file=cabal.project.nothunks.ghc-9.2.4 build vehicle:exe:vehicle
        shell: sh

  # NOTE: This is a temporary workaround, because our tests fail with +nothunks.
  #       Once fixed, we should call build-vehicle with cabal.project.nothunks.
  build-vehicle-ghc-debug:
    name: Linux / GHC 9.2.4 / +ghc-debug
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: "9.2.4"
          cabal-version: "3.8"
          cabal-project-file: cabal.project.ghc-debug.ghc-9.2.4
          cabal-project-freeze-file: cabal.project.ghc-debug.ghc-9.2.4.freeze

      - name: Build Vehicle
        run: cabal --project-file=cabal.project.ghc-debug.ghc-9.2.4 build vehicle:exe:vehicle
        shell: sh
