name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc-version: ["8.10", "9.0"]
        cabal-version: ["3.4"]
        experimental: [false]
        include:
          - os: windows-latest
            experimental: true

    env:
      CABAL_PROJECT_FILE: cabal.project.ghc-${{ matrix.ghc-version }}
      CABAL_PROJECT_FREEZE_FILE: cabal.project.ghc-${{ matrix.ghc-version }}.freeze

    name: Build on ${{ matrix.os }} with GHC ${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: ./.github/actions/setup-haskell
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}
          cabal-project-file: ${{ env.CABAL_PROJECT_FILE }}
          cabal-project-freeze-file: ${{ env.CABAL_PROJECT_FREEZE_FILE }}

      - name: Build Vehicle
        run: cabal v2-run vehicle-build-system build
        shell: bash

      - name: Test Vehicle
        run: cabal v2-run vehicle-build-system basic-tests
        shell: bash

      - name: Copy Vehicle executable to build
        run: |
          mkdir build
          cabal install exe:vehicle \
            --overwrite-policy=always \
            --install-method=copy \
            --installdir=build
        shell: bash

      - name: Upload Vehicle executable (Linux or macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: vehicle-${{ runner.arch }}-${{ runner.os }}-ghc-${{ matrix.ghc-version }}
          path: build/vehicle
          if-no-files-found: error
          
      - name: Upload Vehicle executable (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: vehicle-${{ runner.arch }}-${{ runner.os }}-ghc-${{ matrix.ghc-version }}
          path: build/vehicle.exe
          if-no-files-found: error
