name: Test Marabou integration

on:
  workflow_call:
  workflow_dispatch:

env:
  DEFAULT_GHC_VERSION: "9.4.4"

jobs:
  test-vehicle-marabou:
    name: Test marabou-${{ matrix.os.name }}-${{ matrix.marabou-commit }}
    runs-on: ${{ matrix.os.tag }}

    strategy:
      matrix:
        os:
          - { tag: ubuntu-22.04, name: Linux }
          # - { tag: macos-latest, name: macOS }
          # - { tag: windows-latest, name: Windows }
        marabou-commit: ["663835df7b56be42af94b3d2723bf1b69494c0d5"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Vehicle
        uses: ./.github/actions/setup-vehicle
        with:
          vehicle-artifact-name: |
            vehicle-${{ runner.arch }}-${{ runner.os }}-ghc-${{ env.DEFAULT_GHC_VERSION }}-${{ github.sha }}

      - name: Setup Marabou
        uses: ./.github/actions/setup-marabou
        with:
          marabou-commit: ${{ matrix.marabou-commit }}

      - name: Test Vehicle-Marabou interaction
        run: |
          cabal test                                      \
            vehicle:test:vehicle-integration-tests        \
            --test-option=--color=always                  \
            --test-show-details=always
        shell: sh
