name: Test BumpVer

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: sh

env:
  # NOTE: The default Python version is installed with actions/setup-python.
  DEFAULT_PYTHON_VERSION: "3.11"

jobs:
  test-integration-bumpver:
    name: Test BumpVer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - # Required to run job via act: https://github.com/nektos/act
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "./.github/requirements/test-integration-bumpver.txt"
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - # Required to run job via act: https://github.com/nektos/act
        name: Setup dependencies
        run: pip install -r ./.github/requirements/test-integration-bumpver.txt

      - name: Test BumpVer configuration
        run: pipx run bumpver update --patch --no-fetch --dry
        shell: sh
