name: build vehicle-python

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - # Earliest supported version:
            os: ubuntu-latest
            python-version: "3.7.1"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "vehicle-python/poetry.lock"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-root --with dev
        shell: sh
        working-directory: vehicle-python
        
      - name: Test
        run: |
          tox --skip-missing-interpreters
        shell: sh
        working-directory: vehicle-python
        