-- WARNING: This file was generated automatically by Vehicle
-- and should not be modified manually!
-- Metadata:
--  - Agda version: 2.6.2
--  - Vehicle version: 0.16.0

open import Vehicle
open import Vehicle.Utils
open import Vehicle.Data.Tensor
open import Data.Product
open import Data.Integer as ℤ using (ℤ)
open import Data.Rational as ℚ using (ℚ)
open import Data.Fin as Fin using (Fin; #_)
open import Data.List.Base

module WindControllerSpec where

InputVector : Set
InputVector = Tensor ℚ (2 ∷ [])

currentSensor : Fin 2
currentSensor = # 0

previousSensor : Fin 2
previousSensor = # 1

OutputVector : Set
OutputVector = Tensor ℚ (1 ∷ [])

velocity : Fin 1
velocity = # 0

postulate controller : InputVector → OutputVector

normalise : InputVector → InputVector
normalise x = λ i → (x i ⊕ ℤ.+ 4 ℚ./ 1) ℚ.÷ (ℤ.+ 8 ℚ./ 1)

SafeOutput : InputVector → Set
SafeOutput x =
  let y = controller (normalise x) velocity in
  ℚ.- (ℤ.+ 5 ℚ./ 4) ℚ.< (y ⊕ (ℤ.+ 2 ℚ./ 1) ℚ.* x currentSensor) ⊖ x previousSensor ×
  (y ⊕ (ℤ.+ 2 ℚ./ 1) ℚ.* x currentSensor) ⊖ x previousSensor ℚ.< ℤ.+ 5 ℚ./ 4
