# HLint configuration file
#
# TL;DR
#  HLint is a linter for Haskell. This file should be automatically picked up
#  by your editor, if your editor supports HLint.
#
# See: https://github.com/ndmitchell/hlint

# Ignore some builtin hints
- ignore: { name: Redundant return }
- ignore: { name: Avoid lambda }
- ignore: { name: Redundant <&> }

# Exclude standard IO functions
- functions:
    - {
        name:
          [
            Data.Text.IO.putStrLn,
            Prelude.putStrLn,
            Prelude.stderr,
            Prelude.stdout,
            System.IO.IO,
            System.IO.putStrLn,
            System.IO.stderr,
            System.IO.stdout,
          ],
        within:
          [
            Main,
            Vehicle.Debug,
            Vehicle.Prelude.IO,
            Vehicle.Syntax.Internal.Test,
            Vehicle.Syntax.Internal.ErrM,
            Vehicle.Syntax.Internal.Abs,
            Vehicle.Syntax.External.Test,
            Vehicle.Syntax.External.ErrM,
            Vehicle.Syntax.External.Abs,
          ],
      }
