# HLint configuration file
#
# TL;DR
#  HLint is a linter for Haskell. This file should be automatically picked up
#  by your editor, if your editor supports HLint.
#
# See: https://github.com/ndmitchell/hlint

# Ignore some builtin hints
- ignore: {name: Redundant return}
- ignore: {name: Avoid lambda}
- ignore: {name: Redundant <&>}

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
